// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [467:0] layer4_out_dout;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [191:0] layer5_out_din;
input  [10:0] layer5_out_num_data_valid;
input  [10:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer4_out_read;
reg layer5_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_257_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer4_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [467:0] layer4_out_read_reg_2978;
wire   [0:0] icmp_ln51_fu_388_p2;
reg   [0:0] icmp_ln51_reg_3018;
reg   [0:0] tmp_reg_3023;
wire   [0:0] icmp_ln52_fu_406_p2;
reg   [0:0] icmp_ln52_reg_3030;
reg   [0:0] tmp_169_reg_3035;
wire   [0:0] icmp_ln52_72_fu_430_p2;
reg   [0:0] icmp_ln52_72_reg_3041;
wire   [0:0] icmp_ln52_73_fu_436_p2;
reg   [0:0] icmp_ln52_73_reg_3047;
wire   [0:0] icmp_ln51_24_fu_442_p2;
reg   [0:0] icmp_ln51_24_reg_3053;
reg   [0:0] tmp_171_reg_3058;
wire   [0:0] icmp_ln52_74_fu_466_p2;
reg   [0:0] icmp_ln52_74_reg_3065;
reg   [0:0] tmp_174_reg_3070;
wire   [0:0] icmp_ln52_75_fu_490_p2;
reg   [0:0] icmp_ln52_75_reg_3076;
wire   [0:0] icmp_ln52_76_fu_496_p2;
reg   [0:0] icmp_ln52_76_reg_3082;
wire   [0:0] icmp_ln51_25_fu_502_p2;
reg   [0:0] icmp_ln51_25_reg_3088;
reg   [0:0] tmp_176_reg_3093;
wire   [0:0] icmp_ln52_77_fu_526_p2;
reg   [0:0] icmp_ln52_77_reg_3100;
reg   [0:0] tmp_179_reg_3105;
wire   [0:0] icmp_ln52_78_fu_550_p2;
reg   [0:0] icmp_ln52_78_reg_3111;
wire   [0:0] icmp_ln52_79_fu_556_p2;
reg   [0:0] icmp_ln52_79_reg_3117;
wire   [0:0] icmp_ln51_26_fu_562_p2;
reg   [0:0] icmp_ln51_26_reg_3123;
reg   [0:0] tmp_181_reg_3128;
wire   [0:0] icmp_ln52_80_fu_586_p2;
reg   [0:0] icmp_ln52_80_reg_3135;
reg   [0:0] tmp_184_reg_3140;
wire   [0:0] icmp_ln52_81_fu_610_p2;
reg   [0:0] icmp_ln52_81_reg_3146;
wire   [0:0] icmp_ln52_82_fu_616_p2;
reg   [0:0] icmp_ln52_82_reg_3152;
wire   [0:0] icmp_ln51_27_fu_622_p2;
reg   [0:0] icmp_ln51_27_reg_3158;
reg   [0:0] tmp_186_reg_3163;
wire   [0:0] icmp_ln52_83_fu_646_p2;
reg   [0:0] icmp_ln52_83_reg_3170;
reg   [0:0] tmp_189_reg_3175;
wire   [0:0] icmp_ln52_84_fu_670_p2;
reg   [0:0] icmp_ln52_84_reg_3181;
wire   [0:0] icmp_ln52_85_fu_676_p2;
reg   [0:0] icmp_ln52_85_reg_3187;
wire   [0:0] icmp_ln51_28_fu_682_p2;
reg   [0:0] icmp_ln51_28_reg_3193;
reg   [0:0] tmp_191_reg_3198;
wire   [0:0] icmp_ln52_86_fu_706_p2;
reg   [0:0] icmp_ln52_86_reg_3205;
reg   [0:0] tmp_194_reg_3210;
wire   [0:0] icmp_ln52_87_fu_730_p2;
reg   [0:0] icmp_ln52_87_reg_3216;
wire   [0:0] icmp_ln52_88_fu_736_p2;
reg   [0:0] icmp_ln52_88_reg_3222;
wire   [0:0] icmp_ln51_29_fu_742_p2;
reg   [0:0] icmp_ln51_29_reg_3228;
reg   [0:0] tmp_196_reg_3233;
wire   [0:0] icmp_ln52_89_fu_766_p2;
reg   [0:0] icmp_ln52_89_reg_3240;
reg   [0:0] tmp_199_reg_3245;
wire   [0:0] icmp_ln52_90_fu_790_p2;
reg   [0:0] icmp_ln52_90_reg_3251;
wire   [0:0] icmp_ln52_91_fu_796_p2;
reg   [0:0] icmp_ln52_91_reg_3257;
wire   [0:0] icmp_ln51_30_fu_802_p2;
reg   [0:0] icmp_ln51_30_reg_3263;
reg   [0:0] tmp_201_reg_3268;
wire   [0:0] icmp_ln52_92_fu_826_p2;
reg   [0:0] icmp_ln52_92_reg_3275;
reg   [0:0] tmp_204_reg_3280;
wire   [0:0] icmp_ln52_93_fu_850_p2;
reg   [0:0] icmp_ln52_93_reg_3286;
wire   [0:0] icmp_ln52_94_fu_856_p2;
reg   [0:0] icmp_ln52_94_reg_3292;
wire   [0:0] icmp_ln51_31_fu_862_p2;
reg   [0:0] icmp_ln51_31_reg_3298;
reg   [0:0] tmp_206_reg_3303;
wire   [0:0] icmp_ln52_95_fu_886_p2;
reg   [0:0] icmp_ln52_95_reg_3310;
reg   [0:0] tmp_209_reg_3315;
wire   [0:0] icmp_ln52_96_fu_910_p2;
reg   [0:0] icmp_ln52_96_reg_3321;
wire   [0:0] icmp_ln52_97_fu_916_p2;
reg   [0:0] icmp_ln52_97_reg_3327;
wire   [0:0] icmp_ln51_32_fu_922_p2;
reg   [0:0] icmp_ln51_32_reg_3333;
reg   [0:0] tmp_211_reg_3338;
wire   [0:0] icmp_ln52_98_fu_946_p2;
reg   [0:0] icmp_ln52_98_reg_3345;
reg   [0:0] tmp_214_reg_3350;
wire   [0:0] icmp_ln52_99_fu_970_p2;
reg   [0:0] icmp_ln52_99_reg_3356;
wire   [0:0] icmp_ln52_100_fu_976_p2;
reg   [0:0] icmp_ln52_100_reg_3362;
wire   [0:0] icmp_ln51_33_fu_982_p2;
reg   [0:0] icmp_ln51_33_reg_3368;
reg   [0:0] tmp_216_reg_3373;
wire   [0:0] icmp_ln52_101_fu_1006_p2;
reg   [0:0] icmp_ln52_101_reg_3380;
reg   [0:0] tmp_219_reg_3385;
wire   [0:0] icmp_ln52_102_fu_1030_p2;
reg   [0:0] icmp_ln52_102_reg_3391;
wire   [0:0] icmp_ln52_103_fu_1036_p2;
reg   [0:0] icmp_ln52_103_reg_3397;
wire   [0:0] icmp_ln51_34_fu_1042_p2;
reg   [0:0] icmp_ln51_34_reg_3403;
reg   [0:0] tmp_221_reg_3408;
wire   [0:0] icmp_ln52_104_fu_1066_p2;
reg   [0:0] icmp_ln52_104_reg_3415;
reg   [0:0] tmp_224_reg_3420;
wire   [0:0] icmp_ln52_105_fu_1090_p2;
reg   [0:0] icmp_ln52_105_reg_3426;
wire   [0:0] icmp_ln52_106_fu_1096_p2;
reg   [0:0] icmp_ln52_106_reg_3432;
wire   [15:0] out_data_8_fu_1249_p3;
reg   [15:0] out_data_8_reg_3438;
wire   [15:0] out_data_10_fu_1403_p3;
reg   [15:0] out_data_10_reg_3443;
wire   [15:0] out_data_12_fu_1557_p3;
reg   [15:0] out_data_12_reg_3448;
wire   [15:0] out_data_14_fu_1711_p3;
reg   [15:0] out_data_14_reg_3453;
wire   [15:0] select_ln51_fu_1865_p3;
reg   [15:0] select_ln51_reg_3458;
wire   [15:0] select_ln51_20_fu_2019_p3;
reg   [15:0] select_ln51_20_reg_3463;
wire   [15:0] select_ln51_21_fu_2173_p3;
reg   [15:0] select_ln51_21_reg_3468;
wire   [15:0] select_ln51_22_fu_2327_p3;
reg   [15:0] select_ln51_22_reg_3473;
wire   [15:0] select_ln51_23_fu_2481_p3;
reg   [15:0] select_ln51_23_reg_3478;
wire   [15:0] select_ln51_24_fu_2635_p3;
reg   [15:0] select_ln51_24_reg_3483;
wire   [15:0] select_ln51_25_fu_2789_p3;
reg   [15:0] select_ln51_25_reg_3488;
wire   [15:0] select_ln51_26_fu_2943_p3;
reg   [15:0] select_ln51_26_reg_3493;
reg   [9:0] i_fu_232;
wire   [9:0] i_8_fu_263_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_7;
reg    ap_block_pp0_stage0_01001;
wire   [38:0] trunc_ln44_fu_274_p1;
wire   [7:0] trunc_ln52_fu_402_p1;
wire   [13:0] tmp_s_fu_420_p4;
wire   [38:0] trunc_ln44_s_fu_278_p4;
wire   [7:0] tmp_47_fu_456_p4;
wire   [13:0] tmp_48_fu_480_p4;
wire   [38:0] trunc_ln44_23_fu_288_p4;
wire   [7:0] tmp_49_fu_516_p4;
wire   [13:0] tmp_50_fu_540_p4;
wire   [38:0] trunc_ln44_24_fu_298_p4;
wire   [7:0] tmp_51_fu_576_p4;
wire   [13:0] tmp_52_fu_600_p4;
wire   [38:0] trunc_ln44_25_fu_308_p4;
wire   [7:0] tmp_53_fu_636_p4;
wire   [13:0] tmp_54_fu_660_p4;
wire   [38:0] trunc_ln44_26_fu_318_p4;
wire   [7:0] tmp_55_fu_696_p4;
wire   [13:0] tmp_56_fu_720_p4;
wire   [38:0] trunc_ln44_27_fu_328_p4;
wire   [7:0] tmp_57_fu_756_p4;
wire   [13:0] tmp_58_fu_780_p4;
wire   [38:0] trunc_ln44_28_fu_338_p4;
wire   [7:0] tmp_59_fu_816_p4;
wire   [13:0] tmp_60_fu_840_p4;
wire   [38:0] trunc_ln44_29_fu_348_p4;
wire   [7:0] tmp_61_fu_876_p4;
wire   [13:0] tmp_62_fu_900_p4;
wire   [38:0] trunc_ln44_30_fu_358_p4;
wire   [7:0] tmp_63_fu_936_p4;
wire   [13:0] tmp_64_fu_960_p4;
wire   [38:0] trunc_ln44_31_fu_368_p4;
wire   [7:0] tmp_65_fu_996_p4;
wire   [13:0] tmp_66_fu_1020_p4;
wire   [38:0] trunc_ln44_32_fu_378_p4;
wire   [7:0] tmp_67_fu_1056_p4;
wire   [13:0] tmp_68_fu_1080_p4;
wire   [0:0] tmp_167_fu_1111_p3;
wire   [0:0] or_ln52_fu_1125_p2;
wire   [0:0] tmp_168_fu_1118_p3;
wire   [0:0] and_ln52_fu_1130_p2;
wire   [15:0] trunc_ln5_fu_1102_p4;
wire   [15:0] zext_ln52_fu_1136_p1;
wire   [15:0] add_ln52_fu_1140_p2;
wire   [0:0] tmp_170_fu_1150_p3;
wire   [0:0] select_ln52_fu_1164_p3;
wire   [0:0] select_ln52_144_fu_1170_p3;
wire   [0:0] or_ln52_72_fu_1176_p2;
wire   [0:0] xor_ln52_72_fu_1158_p2;
wire   [0:0] and_ln52_96_fu_1187_p2;
wire   [0:0] and_ln52_48_fu_1192_p2;
wire   [14:0] trunc_ln52_48_fu_1146_p1;
wire   [14:0] select_ln52_96_fu_1203_p3;
wire   [0:0] xor_ln52_48_fu_1197_p2;
wire   [0:0] and_ln52_97_fu_1215_p2;
wire   [0:0] xor_ln52_fu_1181_p2;
wire   [15:0] zext_ln52_48_fu_1211_p1;
wire   [15:0] select_ln52_145_fu_1226_p3;
wire   [0:0] or_ln52_73_fu_1220_p2;
wire   [15:0] select_ln52_97_fu_1233_p3;
wire   [15:0] out_data_fu_1241_p3;
wire   [0:0] tmp_172_fu_1265_p3;
wire   [0:0] or_ln52_74_fu_1279_p2;
wire   [0:0] tmp_173_fu_1272_p3;
wire   [0:0] and_ln52_49_fu_1284_p2;
wire   [15:0] trunc_ln52_s_fu_1256_p4;
wire   [15:0] zext_ln52_24_fu_1290_p1;
wire   [15:0] add_ln52_24_fu_1294_p2;
wire   [0:0] tmp_175_fu_1304_p3;
wire   [0:0] select_ln52_99_fu_1318_p3;
wire   [0:0] select_ln52_147_fu_1324_p3;
wire   [0:0] or_ln52_75_fu_1330_p2;
wire   [0:0] xor_ln52_73_fu_1312_p2;
wire   [0:0] and_ln52_98_fu_1341_p2;
wire   [0:0] and_ln52_50_fu_1346_p2;
wire   [14:0] trunc_ln52_49_fu_1300_p1;
wire   [14:0] select_ln52_100_fu_1357_p3;
wire   [0:0] xor_ln52_50_fu_1351_p2;
wire   [0:0] and_ln52_99_fu_1369_p2;
wire   [0:0] xor_ln52_49_fu_1335_p2;
wire   [15:0] zext_ln52_49_fu_1365_p1;
wire   [15:0] select_ln52_148_fu_1380_p3;
wire   [0:0] or_ln52_76_fu_1374_p2;
wire   [15:0] select_ln52_101_fu_1387_p3;
wire   [15:0] out_data_9_fu_1395_p3;
wire   [0:0] tmp_177_fu_1419_p3;
wire   [0:0] or_ln52_77_fu_1433_p2;
wire   [0:0] tmp_178_fu_1426_p3;
wire   [0:0] and_ln52_51_fu_1438_p2;
wire   [15:0] trunc_ln52_23_fu_1410_p4;
wire   [15:0] zext_ln52_25_fu_1444_p1;
wire   [15:0] add_ln52_25_fu_1448_p2;
wire   [0:0] tmp_180_fu_1458_p3;
wire   [0:0] select_ln52_103_fu_1472_p3;
wire   [0:0] select_ln52_150_fu_1478_p3;
wire   [0:0] or_ln52_78_fu_1484_p2;
wire   [0:0] xor_ln52_74_fu_1466_p2;
wire   [0:0] and_ln52_100_fu_1495_p2;
wire   [0:0] and_ln52_52_fu_1500_p2;
wire   [14:0] trunc_ln52_50_fu_1454_p1;
wire   [14:0] select_ln52_104_fu_1511_p3;
wire   [0:0] xor_ln52_52_fu_1505_p2;
wire   [0:0] and_ln52_101_fu_1523_p2;
wire   [0:0] xor_ln52_51_fu_1489_p2;
wire   [15:0] zext_ln52_50_fu_1519_p1;
wire   [15:0] select_ln52_151_fu_1534_p3;
wire   [0:0] or_ln52_79_fu_1528_p2;
wire   [15:0] select_ln52_105_fu_1541_p3;
wire   [15:0] out_data_11_fu_1549_p3;
wire   [0:0] tmp_182_fu_1573_p3;
wire   [0:0] or_ln52_80_fu_1587_p2;
wire   [0:0] tmp_183_fu_1580_p3;
wire   [0:0] and_ln52_53_fu_1592_p2;
wire   [15:0] trunc_ln52_24_fu_1564_p4;
wire   [15:0] zext_ln52_26_fu_1598_p1;
wire   [15:0] add_ln52_26_fu_1602_p2;
wire   [0:0] tmp_185_fu_1612_p3;
wire   [0:0] select_ln52_107_fu_1626_p3;
wire   [0:0] select_ln52_153_fu_1632_p3;
wire   [0:0] or_ln52_81_fu_1638_p2;
wire   [0:0] xor_ln52_75_fu_1620_p2;
wire   [0:0] and_ln52_102_fu_1649_p2;
wire   [0:0] and_ln52_54_fu_1654_p2;
wire   [14:0] trunc_ln52_51_fu_1608_p1;
wire   [14:0] select_ln52_108_fu_1665_p3;
wire   [0:0] xor_ln52_54_fu_1659_p2;
wire   [0:0] and_ln52_103_fu_1677_p2;
wire   [0:0] xor_ln52_53_fu_1643_p2;
wire   [15:0] zext_ln52_51_fu_1673_p1;
wire   [15:0] select_ln52_154_fu_1688_p3;
wire   [0:0] or_ln52_82_fu_1682_p2;
wire   [15:0] select_ln52_109_fu_1695_p3;
wire   [15:0] out_data_13_fu_1703_p3;
wire   [0:0] tmp_187_fu_1727_p3;
wire   [0:0] or_ln52_83_fu_1741_p2;
wire   [0:0] tmp_188_fu_1734_p3;
wire   [0:0] and_ln52_55_fu_1746_p2;
wire   [15:0] trunc_ln52_25_fu_1718_p4;
wire   [15:0] zext_ln52_27_fu_1752_p1;
wire   [15:0] add_ln52_27_fu_1756_p2;
wire   [0:0] tmp_190_fu_1766_p3;
wire   [0:0] select_ln52_111_fu_1780_p3;
wire   [0:0] select_ln52_156_fu_1786_p3;
wire   [0:0] or_ln52_84_fu_1792_p2;
wire   [0:0] xor_ln52_76_fu_1774_p2;
wire   [0:0] and_ln52_104_fu_1803_p2;
wire   [0:0] and_ln52_56_fu_1808_p2;
wire   [14:0] trunc_ln52_52_fu_1762_p1;
wire   [14:0] select_ln52_112_fu_1819_p3;
wire   [0:0] xor_ln52_56_fu_1813_p2;
wire   [0:0] and_ln52_105_fu_1831_p2;
wire   [0:0] xor_ln52_55_fu_1797_p2;
wire   [15:0] zext_ln52_52_fu_1827_p1;
wire   [15:0] select_ln52_157_fu_1842_p3;
wire   [0:0] or_ln52_85_fu_1836_p2;
wire   [15:0] select_ln52_113_fu_1849_p3;
wire   [15:0] select_ln52_114_fu_1857_p3;
wire   [0:0] tmp_192_fu_1881_p3;
wire   [0:0] or_ln52_86_fu_1895_p2;
wire   [0:0] tmp_193_fu_1888_p3;
wire   [0:0] and_ln52_57_fu_1900_p2;
wire   [15:0] trunc_ln52_26_fu_1872_p4;
wire   [15:0] zext_ln52_28_fu_1906_p1;
wire   [15:0] add_ln52_28_fu_1910_p2;
wire   [0:0] tmp_195_fu_1920_p3;
wire   [0:0] select_ln52_115_fu_1934_p3;
wire   [0:0] select_ln52_158_fu_1940_p3;
wire   [0:0] or_ln52_87_fu_1946_p2;
wire   [0:0] xor_ln52_77_fu_1928_p2;
wire   [0:0] and_ln52_106_fu_1957_p2;
wire   [0:0] and_ln52_58_fu_1962_p2;
wire   [14:0] trunc_ln52_53_fu_1916_p1;
wire   [14:0] select_ln52_116_fu_1973_p3;
wire   [0:0] xor_ln52_58_fu_1967_p2;
wire   [0:0] and_ln52_107_fu_1985_p2;
wire   [0:0] xor_ln52_57_fu_1951_p2;
wire   [15:0] zext_ln52_53_fu_1981_p1;
wire   [15:0] select_ln52_159_fu_1996_p3;
wire   [0:0] or_ln52_88_fu_1990_p2;
wire   [15:0] select_ln52_117_fu_2003_p3;
wire   [15:0] select_ln52_118_fu_2011_p3;
wire   [0:0] tmp_197_fu_2035_p3;
wire   [0:0] or_ln52_89_fu_2049_p2;
wire   [0:0] tmp_198_fu_2042_p3;
wire   [0:0] and_ln52_59_fu_2054_p2;
wire   [15:0] trunc_ln52_27_fu_2026_p4;
wire   [15:0] zext_ln52_29_fu_2060_p1;
wire   [15:0] add_ln52_29_fu_2064_p2;
wire   [0:0] tmp_200_fu_2074_p3;
wire   [0:0] select_ln52_119_fu_2088_p3;
wire   [0:0] select_ln52_160_fu_2094_p3;
wire   [0:0] or_ln52_90_fu_2100_p2;
wire   [0:0] xor_ln52_78_fu_2082_p2;
wire   [0:0] and_ln52_108_fu_2111_p2;
wire   [0:0] and_ln52_60_fu_2116_p2;
wire   [14:0] trunc_ln52_54_fu_2070_p1;
wire   [14:0] select_ln52_120_fu_2127_p3;
wire   [0:0] xor_ln52_60_fu_2121_p2;
wire   [0:0] and_ln52_109_fu_2139_p2;
wire   [0:0] xor_ln52_59_fu_2105_p2;
wire   [15:0] zext_ln52_54_fu_2135_p1;
wire   [15:0] select_ln52_161_fu_2150_p3;
wire   [0:0] or_ln52_91_fu_2144_p2;
wire   [15:0] select_ln52_121_fu_2157_p3;
wire   [15:0] select_ln52_122_fu_2165_p3;
wire   [0:0] tmp_202_fu_2189_p3;
wire   [0:0] or_ln52_92_fu_2203_p2;
wire   [0:0] tmp_203_fu_2196_p3;
wire   [0:0] and_ln52_61_fu_2208_p2;
wire   [15:0] trunc_ln52_28_fu_2180_p4;
wire   [15:0] zext_ln52_30_fu_2214_p1;
wire   [15:0] add_ln52_30_fu_2218_p2;
wire   [0:0] tmp_205_fu_2228_p3;
wire   [0:0] select_ln52_123_fu_2242_p3;
wire   [0:0] select_ln52_162_fu_2248_p3;
wire   [0:0] or_ln52_93_fu_2254_p2;
wire   [0:0] xor_ln52_79_fu_2236_p2;
wire   [0:0] and_ln52_110_fu_2265_p2;
wire   [0:0] and_ln52_62_fu_2270_p2;
wire   [14:0] trunc_ln52_55_fu_2224_p1;
wire   [14:0] select_ln52_124_fu_2281_p3;
wire   [0:0] xor_ln52_62_fu_2275_p2;
wire   [0:0] and_ln52_111_fu_2293_p2;
wire   [0:0] xor_ln52_61_fu_2259_p2;
wire   [15:0] zext_ln52_55_fu_2289_p1;
wire   [15:0] select_ln52_163_fu_2304_p3;
wire   [0:0] or_ln52_94_fu_2298_p2;
wire   [15:0] select_ln52_125_fu_2311_p3;
wire   [15:0] select_ln52_126_fu_2319_p3;
wire   [0:0] tmp_207_fu_2343_p3;
wire   [0:0] or_ln52_95_fu_2357_p2;
wire   [0:0] tmp_208_fu_2350_p3;
wire   [0:0] and_ln52_63_fu_2362_p2;
wire   [15:0] trunc_ln52_29_fu_2334_p4;
wire   [15:0] zext_ln52_31_fu_2368_p1;
wire   [15:0] add_ln52_31_fu_2372_p2;
wire   [0:0] tmp_210_fu_2382_p3;
wire   [0:0] select_ln52_127_fu_2396_p3;
wire   [0:0] select_ln52_164_fu_2402_p3;
wire   [0:0] or_ln52_96_fu_2408_p2;
wire   [0:0] xor_ln52_80_fu_2390_p2;
wire   [0:0] and_ln52_112_fu_2419_p2;
wire   [0:0] and_ln52_64_fu_2424_p2;
wire   [14:0] trunc_ln52_56_fu_2378_p1;
wire   [14:0] select_ln52_128_fu_2435_p3;
wire   [0:0] xor_ln52_64_fu_2429_p2;
wire   [0:0] and_ln52_113_fu_2447_p2;
wire   [0:0] xor_ln52_63_fu_2413_p2;
wire   [15:0] zext_ln52_56_fu_2443_p1;
wire   [15:0] select_ln52_165_fu_2458_p3;
wire   [0:0] or_ln52_97_fu_2452_p2;
wire   [15:0] select_ln52_129_fu_2465_p3;
wire   [15:0] select_ln52_130_fu_2473_p3;
wire   [0:0] tmp_212_fu_2497_p3;
wire   [0:0] or_ln52_98_fu_2511_p2;
wire   [0:0] tmp_213_fu_2504_p3;
wire   [0:0] and_ln52_65_fu_2516_p2;
wire   [15:0] trunc_ln52_30_fu_2488_p4;
wire   [15:0] zext_ln52_32_fu_2522_p1;
wire   [15:0] add_ln52_32_fu_2526_p2;
wire   [0:0] tmp_215_fu_2536_p3;
wire   [0:0] select_ln52_131_fu_2550_p3;
wire   [0:0] select_ln52_166_fu_2556_p3;
wire   [0:0] or_ln52_99_fu_2562_p2;
wire   [0:0] xor_ln52_81_fu_2544_p2;
wire   [0:0] and_ln52_114_fu_2573_p2;
wire   [0:0] and_ln52_66_fu_2578_p2;
wire   [14:0] trunc_ln52_57_fu_2532_p1;
wire   [14:0] select_ln52_132_fu_2589_p3;
wire   [0:0] xor_ln52_66_fu_2583_p2;
wire   [0:0] and_ln52_115_fu_2601_p2;
wire   [0:0] xor_ln52_65_fu_2567_p2;
wire   [15:0] zext_ln52_57_fu_2597_p1;
wire   [15:0] select_ln52_167_fu_2612_p3;
wire   [0:0] or_ln52_100_fu_2606_p2;
wire   [15:0] select_ln52_133_fu_2619_p3;
wire   [15:0] select_ln52_134_fu_2627_p3;
wire   [0:0] tmp_217_fu_2651_p3;
wire   [0:0] or_ln52_101_fu_2665_p2;
wire   [0:0] tmp_218_fu_2658_p3;
wire   [0:0] and_ln52_67_fu_2670_p2;
wire   [15:0] trunc_ln52_31_fu_2642_p4;
wire   [15:0] zext_ln52_33_fu_2676_p1;
wire   [15:0] add_ln52_33_fu_2680_p2;
wire   [0:0] tmp_220_fu_2690_p3;
wire   [0:0] select_ln52_135_fu_2704_p3;
wire   [0:0] select_ln52_168_fu_2710_p3;
wire   [0:0] or_ln52_102_fu_2716_p2;
wire   [0:0] xor_ln52_82_fu_2698_p2;
wire   [0:0] and_ln52_116_fu_2727_p2;
wire   [0:0] and_ln52_68_fu_2732_p2;
wire   [14:0] trunc_ln52_58_fu_2686_p1;
wire   [14:0] select_ln52_136_fu_2743_p3;
wire   [0:0] xor_ln52_68_fu_2737_p2;
wire   [0:0] and_ln52_117_fu_2755_p2;
wire   [0:0] xor_ln52_67_fu_2721_p2;
wire   [15:0] zext_ln52_58_fu_2751_p1;
wire   [15:0] select_ln52_169_fu_2766_p3;
wire   [0:0] or_ln52_103_fu_2760_p2;
wire   [15:0] select_ln52_137_fu_2773_p3;
wire   [15:0] select_ln52_138_fu_2781_p3;
wire   [0:0] tmp_222_fu_2805_p3;
wire   [0:0] or_ln52_104_fu_2819_p2;
wire   [0:0] tmp_223_fu_2812_p3;
wire   [0:0] and_ln52_69_fu_2824_p2;
wire   [15:0] trunc_ln52_32_fu_2796_p4;
wire   [15:0] zext_ln52_34_fu_2830_p1;
wire   [15:0] add_ln52_34_fu_2834_p2;
wire   [0:0] tmp_225_fu_2844_p3;
wire   [0:0] select_ln52_139_fu_2858_p3;
wire   [0:0] select_ln52_170_fu_2864_p3;
wire   [0:0] or_ln52_105_fu_2870_p2;
wire   [0:0] xor_ln52_83_fu_2852_p2;
wire   [0:0] and_ln52_118_fu_2881_p2;
wire   [0:0] and_ln52_70_fu_2886_p2;
wire   [14:0] trunc_ln52_59_fu_2840_p1;
wire   [14:0] select_ln52_140_fu_2897_p3;
wire   [0:0] xor_ln52_70_fu_2891_p2;
wire   [0:0] and_ln52_119_fu_2909_p2;
wire   [0:0] xor_ln52_69_fu_2875_p2;
wire   [15:0] zext_ln52_59_fu_2905_p1;
wire   [15:0] select_ln52_171_fu_2920_p3;
wire   [0:0] or_ln52_106_fu_2914_p2;
wire   [15:0] select_ln52_141_fu_2927_p3;
wire   [15:0] select_ln52_142_fu_2935_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_288;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_232 = 10'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if ((icmp_ln41_fu_257_p2 == 1'd0)) begin
            i_fu_232 <= i_8_fu_263_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_232 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln51_24_reg_3053 <= icmp_ln51_24_fu_442_p2;
        icmp_ln51_25_reg_3088 <= icmp_ln51_25_fu_502_p2;
        icmp_ln51_26_reg_3123 <= icmp_ln51_26_fu_562_p2;
        icmp_ln51_27_reg_3158 <= icmp_ln51_27_fu_622_p2;
        icmp_ln51_28_reg_3193 <= icmp_ln51_28_fu_682_p2;
        icmp_ln51_29_reg_3228 <= icmp_ln51_29_fu_742_p2;
        icmp_ln51_30_reg_3263 <= icmp_ln51_30_fu_802_p2;
        icmp_ln51_31_reg_3298 <= icmp_ln51_31_fu_862_p2;
        icmp_ln51_32_reg_3333 <= icmp_ln51_32_fu_922_p2;
        icmp_ln51_33_reg_3368 <= icmp_ln51_33_fu_982_p2;
        icmp_ln51_34_reg_3403 <= icmp_ln51_34_fu_1042_p2;
        icmp_ln51_reg_3018 <= icmp_ln51_fu_388_p2;
        icmp_ln52_100_reg_3362 <= icmp_ln52_100_fu_976_p2;
        icmp_ln52_101_reg_3380 <= icmp_ln52_101_fu_1006_p2;
        icmp_ln52_102_reg_3391 <= icmp_ln52_102_fu_1030_p2;
        icmp_ln52_103_reg_3397 <= icmp_ln52_103_fu_1036_p2;
        icmp_ln52_104_reg_3415 <= icmp_ln52_104_fu_1066_p2;
        icmp_ln52_105_reg_3426 <= icmp_ln52_105_fu_1090_p2;
        icmp_ln52_106_reg_3432 <= icmp_ln52_106_fu_1096_p2;
        icmp_ln52_72_reg_3041 <= icmp_ln52_72_fu_430_p2;
        icmp_ln52_73_reg_3047 <= icmp_ln52_73_fu_436_p2;
        icmp_ln52_74_reg_3065 <= icmp_ln52_74_fu_466_p2;
        icmp_ln52_75_reg_3076 <= icmp_ln52_75_fu_490_p2;
        icmp_ln52_76_reg_3082 <= icmp_ln52_76_fu_496_p2;
        icmp_ln52_77_reg_3100 <= icmp_ln52_77_fu_526_p2;
        icmp_ln52_78_reg_3111 <= icmp_ln52_78_fu_550_p2;
        icmp_ln52_79_reg_3117 <= icmp_ln52_79_fu_556_p2;
        icmp_ln52_80_reg_3135 <= icmp_ln52_80_fu_586_p2;
        icmp_ln52_81_reg_3146 <= icmp_ln52_81_fu_610_p2;
        icmp_ln52_82_reg_3152 <= icmp_ln52_82_fu_616_p2;
        icmp_ln52_83_reg_3170 <= icmp_ln52_83_fu_646_p2;
        icmp_ln52_84_reg_3181 <= icmp_ln52_84_fu_670_p2;
        icmp_ln52_85_reg_3187 <= icmp_ln52_85_fu_676_p2;
        icmp_ln52_86_reg_3205 <= icmp_ln52_86_fu_706_p2;
        icmp_ln52_87_reg_3216 <= icmp_ln52_87_fu_730_p2;
        icmp_ln52_88_reg_3222 <= icmp_ln52_88_fu_736_p2;
        icmp_ln52_89_reg_3240 <= icmp_ln52_89_fu_766_p2;
        icmp_ln52_90_reg_3251 <= icmp_ln52_90_fu_790_p2;
        icmp_ln52_91_reg_3257 <= icmp_ln52_91_fu_796_p2;
        icmp_ln52_92_reg_3275 <= icmp_ln52_92_fu_826_p2;
        icmp_ln52_93_reg_3286 <= icmp_ln52_93_fu_850_p2;
        icmp_ln52_94_reg_3292 <= icmp_ln52_94_fu_856_p2;
        icmp_ln52_95_reg_3310 <= icmp_ln52_95_fu_886_p2;
        icmp_ln52_96_reg_3321 <= icmp_ln52_96_fu_910_p2;
        icmp_ln52_97_reg_3327 <= icmp_ln52_97_fu_916_p2;
        icmp_ln52_98_reg_3345 <= icmp_ln52_98_fu_946_p2;
        icmp_ln52_99_reg_3356 <= icmp_ln52_99_fu_970_p2;
        icmp_ln52_reg_3030 <= icmp_ln52_fu_406_p2;
        layer4_out_read_reg_2978 <= layer4_out_dout;
        tmp_169_reg_3035 <= layer4_out_dout[32'd24];
        tmp_171_reg_3058 <= layer4_out_dout[32'd77];
        tmp_174_reg_3070 <= layer4_out_dout[32'd63];
        tmp_176_reg_3093 <= layer4_out_dout[32'd116];
        tmp_179_reg_3105 <= layer4_out_dout[32'd102];
        tmp_181_reg_3128 <= layer4_out_dout[32'd155];
        tmp_184_reg_3140 <= layer4_out_dout[32'd141];
        tmp_186_reg_3163 <= layer4_out_dout[32'd194];
        tmp_189_reg_3175 <= layer4_out_dout[32'd180];
        tmp_191_reg_3198 <= layer4_out_dout[32'd233];
        tmp_194_reg_3210 <= layer4_out_dout[32'd219];
        tmp_196_reg_3233 <= layer4_out_dout[32'd272];
        tmp_199_reg_3245 <= layer4_out_dout[32'd258];
        tmp_201_reg_3268 <= layer4_out_dout[32'd311];
        tmp_204_reg_3280 <= layer4_out_dout[32'd297];
        tmp_206_reg_3303 <= layer4_out_dout[32'd350];
        tmp_209_reg_3315 <= layer4_out_dout[32'd336];
        tmp_211_reg_3338 <= layer4_out_dout[32'd389];
        tmp_214_reg_3350 <= layer4_out_dout[32'd375];
        tmp_216_reg_3373 <= layer4_out_dout[32'd428];
        tmp_219_reg_3385 <= layer4_out_dout[32'd414];
        tmp_221_reg_3408 <= layer4_out_dout[32'd467];
        tmp_224_reg_3420 <= layer4_out_dout[32'd453];
        tmp_reg_3023 <= layer4_out_dout[32'd38];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        out_data_10_reg_3443 <= out_data_10_fu_1403_p3;
        out_data_12_reg_3448 <= out_data_12_fu_1557_p3;
        out_data_14_reg_3453 <= out_data_14_fu_1711_p3;
        out_data_8_reg_3438 <= out_data_8_fu_1249_p3;
        select_ln51_20_reg_3463 <= select_ln51_20_fu_2019_p3;
        select_ln51_21_reg_3468 <= select_ln51_21_fu_2173_p3;
        select_ln51_22_reg_3473 <= select_ln51_22_fu_2327_p3;
        select_ln51_23_reg_3478 <= select_ln51_23_fu_2481_p3;
        select_ln51_24_reg_3483 <= select_ln51_24_fu_2635_p3;
        select_ln51_25_reg_3488 <= select_ln51_25_fu_2789_p3;
        select_ln51_26_reg_3493 <= select_ln51_26_fu_2943_p3;
        select_ln51_reg_3458 <= select_ln51_fu_1865_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_257_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_7 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_24_fu_1294_p2 = (trunc_ln52_s_fu_1256_p4 + zext_ln52_24_fu_1290_p1);

assign add_ln52_25_fu_1448_p2 = (trunc_ln52_23_fu_1410_p4 + zext_ln52_25_fu_1444_p1);

assign add_ln52_26_fu_1602_p2 = (trunc_ln52_24_fu_1564_p4 + zext_ln52_26_fu_1598_p1);

assign add_ln52_27_fu_1756_p2 = (trunc_ln52_25_fu_1718_p4 + zext_ln52_27_fu_1752_p1);

assign add_ln52_28_fu_1910_p2 = (trunc_ln52_26_fu_1872_p4 + zext_ln52_28_fu_1906_p1);

assign add_ln52_29_fu_2064_p2 = (trunc_ln52_27_fu_2026_p4 + zext_ln52_29_fu_2060_p1);

assign add_ln52_30_fu_2218_p2 = (trunc_ln52_28_fu_2180_p4 + zext_ln52_30_fu_2214_p1);

assign add_ln52_31_fu_2372_p2 = (trunc_ln52_29_fu_2334_p4 + zext_ln52_31_fu_2368_p1);

assign add_ln52_32_fu_2526_p2 = (trunc_ln52_30_fu_2488_p4 + zext_ln52_32_fu_2522_p1);

assign add_ln52_33_fu_2680_p2 = (trunc_ln52_31_fu_2642_p4 + zext_ln52_33_fu_2676_p1);

assign add_ln52_34_fu_2834_p2 = (trunc_ln52_32_fu_2796_p4 + zext_ln52_34_fu_2830_p1);

assign add_ln52_fu_1140_p2 = (trunc_ln5_fu_1102_p4 + zext_ln52_fu_1136_p1);

assign and_ln52_100_fu_1495_p2 = (xor_ln52_74_fu_1466_p2 & icmp_ln52_78_reg_3111);

assign and_ln52_101_fu_1523_p2 = (xor_ln52_52_fu_1505_p2 & tmp_176_reg_3093);

assign and_ln52_102_fu_1649_p2 = (xor_ln52_75_fu_1620_p2 & icmp_ln52_81_reg_3146);

assign and_ln52_103_fu_1677_p2 = (xor_ln52_54_fu_1659_p2 & tmp_181_reg_3128);

assign and_ln52_104_fu_1803_p2 = (xor_ln52_76_fu_1774_p2 & icmp_ln52_84_reg_3181);

assign and_ln52_105_fu_1831_p2 = (xor_ln52_56_fu_1813_p2 & tmp_186_reg_3163);

assign and_ln52_106_fu_1957_p2 = (xor_ln52_77_fu_1928_p2 & icmp_ln52_87_reg_3216);

assign and_ln52_107_fu_1985_p2 = (xor_ln52_58_fu_1967_p2 & tmp_191_reg_3198);

assign and_ln52_108_fu_2111_p2 = (xor_ln52_78_fu_2082_p2 & icmp_ln52_90_reg_3251);

assign and_ln52_109_fu_2139_p2 = (xor_ln52_60_fu_2121_p2 & tmp_196_reg_3233);

assign and_ln52_110_fu_2265_p2 = (xor_ln52_79_fu_2236_p2 & icmp_ln52_93_reg_3286);

assign and_ln52_111_fu_2293_p2 = (xor_ln52_62_fu_2275_p2 & tmp_201_reg_3268);

assign and_ln52_112_fu_2419_p2 = (xor_ln52_80_fu_2390_p2 & icmp_ln52_96_reg_3321);

assign and_ln52_113_fu_2447_p2 = (xor_ln52_64_fu_2429_p2 & tmp_206_reg_3303);

assign and_ln52_114_fu_2573_p2 = (xor_ln52_81_fu_2544_p2 & icmp_ln52_99_reg_3356);

assign and_ln52_115_fu_2601_p2 = (xor_ln52_66_fu_2583_p2 & tmp_211_reg_3338);

assign and_ln52_116_fu_2727_p2 = (xor_ln52_82_fu_2698_p2 & icmp_ln52_102_reg_3391);

assign and_ln52_117_fu_2755_p2 = (xor_ln52_68_fu_2737_p2 & tmp_216_reg_3373);

assign and_ln52_118_fu_2881_p2 = (xor_ln52_83_fu_2852_p2 & icmp_ln52_105_reg_3426);

assign and_ln52_119_fu_2909_p2 = (xor_ln52_70_fu_2891_p2 & tmp_221_reg_3408);

assign and_ln52_48_fu_1192_p2 = (tmp_169_reg_3035 & and_ln52_96_fu_1187_p2);

assign and_ln52_49_fu_1284_p2 = (tmp_173_fu_1272_p3 & or_ln52_74_fu_1279_p2);

assign and_ln52_50_fu_1346_p2 = (tmp_174_reg_3070 & and_ln52_98_fu_1341_p2);

assign and_ln52_51_fu_1438_p2 = (tmp_178_fu_1426_p3 & or_ln52_77_fu_1433_p2);

assign and_ln52_52_fu_1500_p2 = (tmp_179_reg_3105 & and_ln52_100_fu_1495_p2);

assign and_ln52_53_fu_1592_p2 = (tmp_183_fu_1580_p3 & or_ln52_80_fu_1587_p2);

assign and_ln52_54_fu_1654_p2 = (tmp_184_reg_3140 & and_ln52_102_fu_1649_p2);

assign and_ln52_55_fu_1746_p2 = (tmp_188_fu_1734_p3 & or_ln52_83_fu_1741_p2);

assign and_ln52_56_fu_1808_p2 = (tmp_189_reg_3175 & and_ln52_104_fu_1803_p2);

assign and_ln52_57_fu_1900_p2 = (tmp_193_fu_1888_p3 & or_ln52_86_fu_1895_p2);

assign and_ln52_58_fu_1962_p2 = (tmp_194_reg_3210 & and_ln52_106_fu_1957_p2);

assign and_ln52_59_fu_2054_p2 = (tmp_198_fu_2042_p3 & or_ln52_89_fu_2049_p2);

assign and_ln52_60_fu_2116_p2 = (tmp_199_reg_3245 & and_ln52_108_fu_2111_p2);

assign and_ln52_61_fu_2208_p2 = (tmp_203_fu_2196_p3 & or_ln52_92_fu_2203_p2);

assign and_ln52_62_fu_2270_p2 = (tmp_204_reg_3280 & and_ln52_110_fu_2265_p2);

assign and_ln52_63_fu_2362_p2 = (tmp_208_fu_2350_p3 & or_ln52_95_fu_2357_p2);

assign and_ln52_64_fu_2424_p2 = (tmp_209_reg_3315 & and_ln52_112_fu_2419_p2);

assign and_ln52_65_fu_2516_p2 = (tmp_213_fu_2504_p3 & or_ln52_98_fu_2511_p2);

assign and_ln52_66_fu_2578_p2 = (tmp_214_reg_3350 & and_ln52_114_fu_2573_p2);

assign and_ln52_67_fu_2670_p2 = (tmp_218_fu_2658_p3 & or_ln52_101_fu_2665_p2);

assign and_ln52_68_fu_2732_p2 = (tmp_219_reg_3385 & and_ln52_116_fu_2727_p2);

assign and_ln52_69_fu_2824_p2 = (tmp_223_fu_2812_p3 & or_ln52_104_fu_2819_p2);

assign and_ln52_70_fu_2886_p2 = (tmp_224_reg_3420 & and_ln52_118_fu_2881_p2);

assign and_ln52_96_fu_1187_p2 = (xor_ln52_72_fu_1158_p2 & icmp_ln52_72_reg_3041);

assign and_ln52_97_fu_1215_p2 = (xor_ln52_48_fu_1197_p2 & tmp_reg_3023);

assign and_ln52_98_fu_1341_p2 = (xor_ln52_73_fu_1312_p2 & icmp_ln52_75_reg_3076);

assign and_ln52_99_fu_1369_p2 = (xor_ln52_50_fu_1351_p2 & tmp_171_reg_3058);

assign and_ln52_fu_1130_p2 = (tmp_168_fu_1118_p3 & or_ln52_fu_1125_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer4_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (layer5_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_288 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_8_fu_263_p2 = (ap_sig_allocacmp_i_7 + 10'd1);

assign icmp_ln41_fu_257_p2 = ((ap_sig_allocacmp_i_7 == 10'd864) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_442_p2 = (($signed(trunc_ln44_s_fu_278_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_502_p2 = (($signed(trunc_ln44_23_fu_288_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_562_p2 = (($signed(trunc_ln44_24_fu_298_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_622_p2 = (($signed(trunc_ln44_25_fu_308_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_682_p2 = (($signed(trunc_ln44_26_fu_318_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_742_p2 = (($signed(trunc_ln44_27_fu_328_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_802_p2 = (($signed(trunc_ln44_28_fu_338_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_862_p2 = (($signed(trunc_ln44_29_fu_348_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_922_p2 = (($signed(trunc_ln44_30_fu_358_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_982_p2 = (($signed(trunc_ln44_31_fu_368_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1042_p2 = (($signed(trunc_ln44_32_fu_378_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_388_p2 = (($signed(trunc_ln44_fu_274_p1) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_100_fu_976_p2 = ((tmp_64_fu_960_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_101_fu_1006_p2 = ((tmp_65_fu_996_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_102_fu_1030_p2 = ((tmp_66_fu_1020_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_103_fu_1036_p2 = ((tmp_66_fu_1020_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_104_fu_1066_p2 = ((tmp_67_fu_1056_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_105_fu_1090_p2 = ((tmp_68_fu_1080_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_106_fu_1096_p2 = ((tmp_68_fu_1080_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_72_fu_430_p2 = ((tmp_s_fu_420_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_73_fu_436_p2 = ((tmp_s_fu_420_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_74_fu_466_p2 = ((tmp_47_fu_456_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_75_fu_490_p2 = ((tmp_48_fu_480_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_76_fu_496_p2 = ((tmp_48_fu_480_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_77_fu_526_p2 = ((tmp_49_fu_516_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_78_fu_550_p2 = ((tmp_50_fu_540_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_79_fu_556_p2 = ((tmp_50_fu_540_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_80_fu_586_p2 = ((tmp_51_fu_576_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_81_fu_610_p2 = ((tmp_52_fu_600_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_82_fu_616_p2 = ((tmp_52_fu_600_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_83_fu_646_p2 = ((tmp_53_fu_636_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_84_fu_670_p2 = ((tmp_54_fu_660_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_85_fu_676_p2 = ((tmp_54_fu_660_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_86_fu_706_p2 = ((tmp_55_fu_696_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_87_fu_730_p2 = ((tmp_56_fu_720_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_88_fu_736_p2 = ((tmp_56_fu_720_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_89_fu_766_p2 = ((tmp_57_fu_756_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_90_fu_790_p2 = ((tmp_58_fu_780_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_91_fu_796_p2 = ((tmp_58_fu_780_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_92_fu_826_p2 = ((tmp_59_fu_816_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_93_fu_850_p2 = ((tmp_60_fu_840_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_94_fu_856_p2 = ((tmp_60_fu_840_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_95_fu_886_p2 = ((tmp_61_fu_876_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_96_fu_910_p2 = ((tmp_62_fu_900_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_97_fu_916_p2 = ((tmp_62_fu_900_p4 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_98_fu_946_p2 = ((tmp_63_fu_936_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_99_fu_970_p2 = ((tmp_64_fu_960_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_406_p2 = ((trunc_ln52_fu_402_p1 != 8'd0) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{{{{{{{select_ln51_26_reg_3493}, {select_ln51_25_reg_3488}}, {select_ln51_24_reg_3483}}, {select_ln51_23_reg_3478}}, {select_ln51_22_reg_3473}}, {select_ln51_21_reg_3468}}, {select_ln51_20_reg_3463}}, {select_ln51_reg_3458}}, {out_data_14_reg_3453}}, {out_data_12_reg_3448}}, {out_data_10_reg_3443}}, {out_data_8_reg_3438}};

assign or_ln52_100_fu_2606_p2 = (xor_ln52_65_fu_2567_p2 | and_ln52_115_fu_2601_p2);

assign or_ln52_101_fu_2665_p2 = (tmp_217_fu_2651_p3 | icmp_ln52_101_reg_3380);

assign or_ln52_102_fu_2716_p2 = (tmp_216_reg_3373 | select_ln52_168_fu_2710_p3);

assign or_ln52_103_fu_2760_p2 = (xor_ln52_67_fu_2721_p2 | and_ln52_117_fu_2755_p2);

assign or_ln52_104_fu_2819_p2 = (tmp_222_fu_2805_p3 | icmp_ln52_104_reg_3415);

assign or_ln52_105_fu_2870_p2 = (tmp_221_reg_3408 | select_ln52_170_fu_2864_p3);

assign or_ln52_106_fu_2914_p2 = (xor_ln52_69_fu_2875_p2 | and_ln52_119_fu_2909_p2);

assign or_ln52_72_fu_1176_p2 = (tmp_reg_3023 | select_ln52_144_fu_1170_p3);

assign or_ln52_73_fu_1220_p2 = (xor_ln52_fu_1181_p2 | and_ln52_97_fu_1215_p2);

assign or_ln52_74_fu_1279_p2 = (tmp_172_fu_1265_p3 | icmp_ln52_74_reg_3065);

assign or_ln52_75_fu_1330_p2 = (tmp_171_reg_3058 | select_ln52_147_fu_1324_p3);

assign or_ln52_76_fu_1374_p2 = (xor_ln52_49_fu_1335_p2 | and_ln52_99_fu_1369_p2);

assign or_ln52_77_fu_1433_p2 = (tmp_177_fu_1419_p3 | icmp_ln52_77_reg_3100);

assign or_ln52_78_fu_1484_p2 = (tmp_176_reg_3093 | select_ln52_150_fu_1478_p3);

assign or_ln52_79_fu_1528_p2 = (xor_ln52_51_fu_1489_p2 | and_ln52_101_fu_1523_p2);

assign or_ln52_80_fu_1587_p2 = (tmp_182_fu_1573_p3 | icmp_ln52_80_reg_3135);

assign or_ln52_81_fu_1638_p2 = (tmp_181_reg_3128 | select_ln52_153_fu_1632_p3);

assign or_ln52_82_fu_1682_p2 = (xor_ln52_53_fu_1643_p2 | and_ln52_103_fu_1677_p2);

assign or_ln52_83_fu_1741_p2 = (tmp_187_fu_1727_p3 | icmp_ln52_83_reg_3170);

assign or_ln52_84_fu_1792_p2 = (tmp_186_reg_3163 | select_ln52_156_fu_1786_p3);

assign or_ln52_85_fu_1836_p2 = (xor_ln52_55_fu_1797_p2 | and_ln52_105_fu_1831_p2);

assign or_ln52_86_fu_1895_p2 = (tmp_192_fu_1881_p3 | icmp_ln52_86_reg_3205);

assign or_ln52_87_fu_1946_p2 = (tmp_191_reg_3198 | select_ln52_158_fu_1940_p3);

assign or_ln52_88_fu_1990_p2 = (xor_ln52_57_fu_1951_p2 | and_ln52_107_fu_1985_p2);

assign or_ln52_89_fu_2049_p2 = (tmp_197_fu_2035_p3 | icmp_ln52_89_reg_3240);

assign or_ln52_90_fu_2100_p2 = (tmp_196_reg_3233 | select_ln52_160_fu_2094_p3);

assign or_ln52_91_fu_2144_p2 = (xor_ln52_59_fu_2105_p2 | and_ln52_109_fu_2139_p2);

assign or_ln52_92_fu_2203_p2 = (tmp_202_fu_2189_p3 | icmp_ln52_92_reg_3275);

assign or_ln52_93_fu_2254_p2 = (tmp_201_reg_3268 | select_ln52_162_fu_2248_p3);

assign or_ln52_94_fu_2298_p2 = (xor_ln52_61_fu_2259_p2 | and_ln52_111_fu_2293_p2);

assign or_ln52_95_fu_2357_p2 = (tmp_207_fu_2343_p3 | icmp_ln52_95_reg_3310);

assign or_ln52_96_fu_2408_p2 = (tmp_206_reg_3303 | select_ln52_164_fu_2402_p3);

assign or_ln52_97_fu_2452_p2 = (xor_ln52_63_fu_2413_p2 | and_ln52_113_fu_2447_p2);

assign or_ln52_98_fu_2511_p2 = (tmp_212_fu_2497_p3 | icmp_ln52_98_reg_3345);

assign or_ln52_99_fu_2562_p2 = (tmp_211_reg_3338 | select_ln52_166_fu_2556_p3);

assign or_ln52_fu_1125_p2 = (tmp_167_fu_1111_p3 | icmp_ln52_reg_3030);

assign out_data_10_fu_1403_p3 = ((icmp_ln51_24_reg_3053[0:0] == 1'b1) ? out_data_9_fu_1395_p3 : 16'd0);

assign out_data_11_fu_1549_p3 = ((or_ln52_79_fu_1528_p2[0:0] == 1'b1) ? select_ln52_105_fu_1541_p3 : add_ln52_25_fu_1448_p2);

assign out_data_12_fu_1557_p3 = ((icmp_ln51_25_reg_3088[0:0] == 1'b1) ? out_data_11_fu_1549_p3 : 16'd0);

assign out_data_13_fu_1703_p3 = ((or_ln52_82_fu_1682_p2[0:0] == 1'b1) ? select_ln52_109_fu_1695_p3 : add_ln52_26_fu_1602_p2);

assign out_data_14_fu_1711_p3 = ((icmp_ln51_26_reg_3123[0:0] == 1'b1) ? out_data_13_fu_1703_p3 : 16'd0);

assign out_data_8_fu_1249_p3 = ((icmp_ln51_reg_3018[0:0] == 1'b1) ? out_data_fu_1241_p3 : 16'd0);

assign out_data_9_fu_1395_p3 = ((or_ln52_76_fu_1374_p2[0:0] == 1'b1) ? select_ln52_101_fu_1387_p3 : add_ln52_24_fu_1294_p2);

assign out_data_fu_1241_p3 = ((or_ln52_73_fu_1220_p2[0:0] == 1'b1) ? select_ln52_97_fu_1233_p3 : add_ln52_fu_1140_p2);

assign select_ln51_20_fu_2019_p3 = ((icmp_ln51_28_reg_3193[0:0] == 1'b1) ? select_ln52_118_fu_2011_p3 : 16'd0);

assign select_ln51_21_fu_2173_p3 = ((icmp_ln51_29_reg_3228[0:0] == 1'b1) ? select_ln52_122_fu_2165_p3 : 16'd0);

assign select_ln51_22_fu_2327_p3 = ((icmp_ln51_30_reg_3263[0:0] == 1'b1) ? select_ln52_126_fu_2319_p3 : 16'd0);

assign select_ln51_23_fu_2481_p3 = ((icmp_ln51_31_reg_3298[0:0] == 1'b1) ? select_ln52_130_fu_2473_p3 : 16'd0);

assign select_ln51_24_fu_2635_p3 = ((icmp_ln51_32_reg_3333[0:0] == 1'b1) ? select_ln52_134_fu_2627_p3 : 16'd0);

assign select_ln51_25_fu_2789_p3 = ((icmp_ln51_33_reg_3368[0:0] == 1'b1) ? select_ln52_138_fu_2781_p3 : 16'd0);

assign select_ln51_26_fu_2943_p3 = ((icmp_ln51_34_reg_3403[0:0] == 1'b1) ? select_ln52_142_fu_2935_p3 : 16'd0);

assign select_ln51_fu_1865_p3 = ((icmp_ln51_27_reg_3158[0:0] == 1'b1) ? select_ln52_114_fu_1857_p3 : 16'd0);

assign select_ln52_100_fu_1357_p3 = ((and_ln52_50_fu_1346_p2[0:0] == 1'b1) ? trunc_ln52_49_fu_1300_p1 : 15'd0);

assign select_ln52_101_fu_1387_p3 = ((or_ln52_75_fu_1330_p2[0:0] == 1'b1) ? select_ln52_148_fu_1380_p3 : 16'd65535);

assign select_ln52_103_fu_1472_p3 = ((tmp_180_fu_1458_p3[0:0] == 1'b1) ? icmp_ln52_79_reg_3117 : icmp_ln52_78_reg_3111);

assign select_ln52_104_fu_1511_p3 = ((and_ln52_52_fu_1500_p2[0:0] == 1'b1) ? trunc_ln52_50_fu_1454_p1 : 15'd0);

assign select_ln52_105_fu_1541_p3 = ((or_ln52_78_fu_1484_p2[0:0] == 1'b1) ? select_ln52_151_fu_1534_p3 : 16'd65535);

assign select_ln52_107_fu_1626_p3 = ((tmp_185_fu_1612_p3[0:0] == 1'b1) ? icmp_ln52_82_reg_3152 : icmp_ln52_81_reg_3146);

assign select_ln52_108_fu_1665_p3 = ((and_ln52_54_fu_1654_p2[0:0] == 1'b1) ? trunc_ln52_51_fu_1608_p1 : 15'd0);

assign select_ln52_109_fu_1695_p3 = ((or_ln52_81_fu_1638_p2[0:0] == 1'b1) ? select_ln52_154_fu_1688_p3 : 16'd65535);

assign select_ln52_111_fu_1780_p3 = ((tmp_190_fu_1766_p3[0:0] == 1'b1) ? icmp_ln52_85_reg_3187 : icmp_ln52_84_reg_3181);

assign select_ln52_112_fu_1819_p3 = ((and_ln52_56_fu_1808_p2[0:0] == 1'b1) ? trunc_ln52_52_fu_1762_p1 : 15'd0);

assign select_ln52_113_fu_1849_p3 = ((or_ln52_84_fu_1792_p2[0:0] == 1'b1) ? select_ln52_157_fu_1842_p3 : 16'd65535);

assign select_ln52_114_fu_1857_p3 = ((or_ln52_85_fu_1836_p2[0:0] == 1'b1) ? select_ln52_113_fu_1849_p3 : add_ln52_27_fu_1756_p2);

assign select_ln52_115_fu_1934_p3 = ((tmp_195_fu_1920_p3[0:0] == 1'b1) ? icmp_ln52_88_reg_3222 : icmp_ln52_87_reg_3216);

assign select_ln52_116_fu_1973_p3 = ((and_ln52_58_fu_1962_p2[0:0] == 1'b1) ? trunc_ln52_53_fu_1916_p1 : 15'd0);

assign select_ln52_117_fu_2003_p3 = ((or_ln52_87_fu_1946_p2[0:0] == 1'b1) ? select_ln52_159_fu_1996_p3 : 16'd65535);

assign select_ln52_118_fu_2011_p3 = ((or_ln52_88_fu_1990_p2[0:0] == 1'b1) ? select_ln52_117_fu_2003_p3 : add_ln52_28_fu_1910_p2);

assign select_ln52_119_fu_2088_p3 = ((tmp_200_fu_2074_p3[0:0] == 1'b1) ? icmp_ln52_91_reg_3257 : icmp_ln52_90_reg_3251);

assign select_ln52_120_fu_2127_p3 = ((and_ln52_60_fu_2116_p2[0:0] == 1'b1) ? trunc_ln52_54_fu_2070_p1 : 15'd0);

assign select_ln52_121_fu_2157_p3 = ((or_ln52_90_fu_2100_p2[0:0] == 1'b1) ? select_ln52_161_fu_2150_p3 : 16'd65535);

assign select_ln52_122_fu_2165_p3 = ((or_ln52_91_fu_2144_p2[0:0] == 1'b1) ? select_ln52_121_fu_2157_p3 : add_ln52_29_fu_2064_p2);

assign select_ln52_123_fu_2242_p3 = ((tmp_205_fu_2228_p3[0:0] == 1'b1) ? icmp_ln52_94_reg_3292 : icmp_ln52_93_reg_3286);

assign select_ln52_124_fu_2281_p3 = ((and_ln52_62_fu_2270_p2[0:0] == 1'b1) ? trunc_ln52_55_fu_2224_p1 : 15'd0);

assign select_ln52_125_fu_2311_p3 = ((or_ln52_93_fu_2254_p2[0:0] == 1'b1) ? select_ln52_163_fu_2304_p3 : 16'd65535);

assign select_ln52_126_fu_2319_p3 = ((or_ln52_94_fu_2298_p2[0:0] == 1'b1) ? select_ln52_125_fu_2311_p3 : add_ln52_30_fu_2218_p2);

assign select_ln52_127_fu_2396_p3 = ((tmp_210_fu_2382_p3[0:0] == 1'b1) ? icmp_ln52_97_reg_3327 : icmp_ln52_96_reg_3321);

assign select_ln52_128_fu_2435_p3 = ((and_ln52_64_fu_2424_p2[0:0] == 1'b1) ? trunc_ln52_56_fu_2378_p1 : 15'd0);

assign select_ln52_129_fu_2465_p3 = ((or_ln52_96_fu_2408_p2[0:0] == 1'b1) ? select_ln52_165_fu_2458_p3 : 16'd65535);

assign select_ln52_130_fu_2473_p3 = ((or_ln52_97_fu_2452_p2[0:0] == 1'b1) ? select_ln52_129_fu_2465_p3 : add_ln52_31_fu_2372_p2);

assign select_ln52_131_fu_2550_p3 = ((tmp_215_fu_2536_p3[0:0] == 1'b1) ? icmp_ln52_100_reg_3362 : icmp_ln52_99_reg_3356);

assign select_ln52_132_fu_2589_p3 = ((and_ln52_66_fu_2578_p2[0:0] == 1'b1) ? trunc_ln52_57_fu_2532_p1 : 15'd0);

assign select_ln52_133_fu_2619_p3 = ((or_ln52_99_fu_2562_p2[0:0] == 1'b1) ? select_ln52_167_fu_2612_p3 : 16'd65535);

assign select_ln52_134_fu_2627_p3 = ((or_ln52_100_fu_2606_p2[0:0] == 1'b1) ? select_ln52_133_fu_2619_p3 : add_ln52_32_fu_2526_p2);

assign select_ln52_135_fu_2704_p3 = ((tmp_220_fu_2690_p3[0:0] == 1'b1) ? icmp_ln52_103_reg_3397 : icmp_ln52_102_reg_3391);

assign select_ln52_136_fu_2743_p3 = ((and_ln52_68_fu_2732_p2[0:0] == 1'b1) ? trunc_ln52_58_fu_2686_p1 : 15'd0);

assign select_ln52_137_fu_2773_p3 = ((or_ln52_102_fu_2716_p2[0:0] == 1'b1) ? select_ln52_169_fu_2766_p3 : 16'd65535);

assign select_ln52_138_fu_2781_p3 = ((or_ln52_103_fu_2760_p2[0:0] == 1'b1) ? select_ln52_137_fu_2773_p3 : add_ln52_33_fu_2680_p2);

assign select_ln52_139_fu_2858_p3 = ((tmp_225_fu_2844_p3[0:0] == 1'b1) ? icmp_ln52_106_reg_3432 : icmp_ln52_105_reg_3426);

assign select_ln52_140_fu_2897_p3 = ((and_ln52_70_fu_2886_p2[0:0] == 1'b1) ? trunc_ln52_59_fu_2840_p1 : 15'd0);

assign select_ln52_141_fu_2927_p3 = ((or_ln52_105_fu_2870_p2[0:0] == 1'b1) ? select_ln52_171_fu_2920_p3 : 16'd65535);

assign select_ln52_142_fu_2935_p3 = ((or_ln52_106_fu_2914_p2[0:0] == 1'b1) ? select_ln52_141_fu_2927_p3 : add_ln52_34_fu_2834_p2);

assign select_ln52_144_fu_1170_p3 = ((tmp_169_reg_3035[0:0] == 1'b1) ? select_ln52_fu_1164_p3 : icmp_ln52_73_reg_3047);

assign select_ln52_145_fu_1226_p3 = ((tmp_reg_3023[0:0] == 1'b1) ? zext_ln52_48_fu_1211_p1 : add_ln52_fu_1140_p2);

assign select_ln52_147_fu_1324_p3 = ((tmp_174_reg_3070[0:0] == 1'b1) ? select_ln52_99_fu_1318_p3 : icmp_ln52_76_reg_3082);

assign select_ln52_148_fu_1380_p3 = ((tmp_171_reg_3058[0:0] == 1'b1) ? zext_ln52_49_fu_1365_p1 : add_ln52_24_fu_1294_p2);

assign select_ln52_150_fu_1478_p3 = ((tmp_179_reg_3105[0:0] == 1'b1) ? select_ln52_103_fu_1472_p3 : icmp_ln52_79_reg_3117);

assign select_ln52_151_fu_1534_p3 = ((tmp_176_reg_3093[0:0] == 1'b1) ? zext_ln52_50_fu_1519_p1 : add_ln52_25_fu_1448_p2);

assign select_ln52_153_fu_1632_p3 = ((tmp_184_reg_3140[0:0] == 1'b1) ? select_ln52_107_fu_1626_p3 : icmp_ln52_82_reg_3152);

assign select_ln52_154_fu_1688_p3 = ((tmp_181_reg_3128[0:0] == 1'b1) ? zext_ln52_51_fu_1673_p1 : add_ln52_26_fu_1602_p2);

assign select_ln52_156_fu_1786_p3 = ((tmp_189_reg_3175[0:0] == 1'b1) ? select_ln52_111_fu_1780_p3 : icmp_ln52_85_reg_3187);

assign select_ln52_157_fu_1842_p3 = ((tmp_186_reg_3163[0:0] == 1'b1) ? zext_ln52_52_fu_1827_p1 : add_ln52_27_fu_1756_p2);

assign select_ln52_158_fu_1940_p3 = ((tmp_194_reg_3210[0:0] == 1'b1) ? select_ln52_115_fu_1934_p3 : icmp_ln52_88_reg_3222);

assign select_ln52_159_fu_1996_p3 = ((tmp_191_reg_3198[0:0] == 1'b1) ? zext_ln52_53_fu_1981_p1 : add_ln52_28_fu_1910_p2);

assign select_ln52_160_fu_2094_p3 = ((tmp_199_reg_3245[0:0] == 1'b1) ? select_ln52_119_fu_2088_p3 : icmp_ln52_91_reg_3257);

assign select_ln52_161_fu_2150_p3 = ((tmp_196_reg_3233[0:0] == 1'b1) ? zext_ln52_54_fu_2135_p1 : add_ln52_29_fu_2064_p2);

assign select_ln52_162_fu_2248_p3 = ((tmp_204_reg_3280[0:0] == 1'b1) ? select_ln52_123_fu_2242_p3 : icmp_ln52_94_reg_3292);

assign select_ln52_163_fu_2304_p3 = ((tmp_201_reg_3268[0:0] == 1'b1) ? zext_ln52_55_fu_2289_p1 : add_ln52_30_fu_2218_p2);

assign select_ln52_164_fu_2402_p3 = ((tmp_209_reg_3315[0:0] == 1'b1) ? select_ln52_127_fu_2396_p3 : icmp_ln52_97_reg_3327);

assign select_ln52_165_fu_2458_p3 = ((tmp_206_reg_3303[0:0] == 1'b1) ? zext_ln52_56_fu_2443_p1 : add_ln52_31_fu_2372_p2);

assign select_ln52_166_fu_2556_p3 = ((tmp_214_reg_3350[0:0] == 1'b1) ? select_ln52_131_fu_2550_p3 : icmp_ln52_100_reg_3362);

assign select_ln52_167_fu_2612_p3 = ((tmp_211_reg_3338[0:0] == 1'b1) ? zext_ln52_57_fu_2597_p1 : add_ln52_32_fu_2526_p2);

assign select_ln52_168_fu_2710_p3 = ((tmp_219_reg_3385[0:0] == 1'b1) ? select_ln52_135_fu_2704_p3 : icmp_ln52_103_reg_3397);

assign select_ln52_169_fu_2766_p3 = ((tmp_216_reg_3373[0:0] == 1'b1) ? zext_ln52_58_fu_2751_p1 : add_ln52_33_fu_2680_p2);

assign select_ln52_170_fu_2864_p3 = ((tmp_224_reg_3420[0:0] == 1'b1) ? select_ln52_139_fu_2858_p3 : icmp_ln52_106_reg_3432);

assign select_ln52_171_fu_2920_p3 = ((tmp_221_reg_3408[0:0] == 1'b1) ? zext_ln52_59_fu_2905_p1 : add_ln52_34_fu_2834_p2);

assign select_ln52_96_fu_1203_p3 = ((and_ln52_48_fu_1192_p2[0:0] == 1'b1) ? trunc_ln52_48_fu_1146_p1 : 15'd0);

assign select_ln52_97_fu_1233_p3 = ((or_ln52_72_fu_1176_p2[0:0] == 1'b1) ? select_ln52_145_fu_1226_p3 : 16'd65535);

assign select_ln52_99_fu_1318_p3 = ((tmp_175_fu_1304_p3[0:0] == 1'b1) ? icmp_ln52_76_reg_3082 : icmp_ln52_75_reg_3076);

assign select_ln52_fu_1164_p3 = ((tmp_170_fu_1150_p3[0:0] == 1'b1) ? icmp_ln52_73_reg_3047 : icmp_ln52_72_reg_3041);

assign start_out = real_start;

assign tmp_167_fu_1111_p3 = layer4_out_read_reg_2978[32'd9];

assign tmp_168_fu_1118_p3 = layer4_out_read_reg_2978[32'd8];

assign tmp_170_fu_1150_p3 = add_ln52_fu_1140_p2[32'd15];

assign tmp_172_fu_1265_p3 = layer4_out_read_reg_2978[32'd48];

assign tmp_173_fu_1272_p3 = layer4_out_read_reg_2978[32'd47];

assign tmp_175_fu_1304_p3 = add_ln52_24_fu_1294_p2[32'd15];

assign tmp_177_fu_1419_p3 = layer4_out_read_reg_2978[32'd87];

assign tmp_178_fu_1426_p3 = layer4_out_read_reg_2978[32'd86];

assign tmp_180_fu_1458_p3 = add_ln52_25_fu_1448_p2[32'd15];

assign tmp_182_fu_1573_p3 = layer4_out_read_reg_2978[32'd126];

assign tmp_183_fu_1580_p3 = layer4_out_read_reg_2978[32'd125];

assign tmp_185_fu_1612_p3 = add_ln52_26_fu_1602_p2[32'd15];

assign tmp_187_fu_1727_p3 = layer4_out_read_reg_2978[32'd165];

assign tmp_188_fu_1734_p3 = layer4_out_read_reg_2978[32'd164];

assign tmp_190_fu_1766_p3 = add_ln52_27_fu_1756_p2[32'd15];

assign tmp_192_fu_1881_p3 = layer4_out_read_reg_2978[32'd204];

assign tmp_193_fu_1888_p3 = layer4_out_read_reg_2978[32'd203];

assign tmp_195_fu_1920_p3 = add_ln52_28_fu_1910_p2[32'd15];

assign tmp_197_fu_2035_p3 = layer4_out_read_reg_2978[32'd243];

assign tmp_198_fu_2042_p3 = layer4_out_read_reg_2978[32'd242];

assign tmp_200_fu_2074_p3 = add_ln52_29_fu_2064_p2[32'd15];

assign tmp_202_fu_2189_p3 = layer4_out_read_reg_2978[32'd282];

assign tmp_203_fu_2196_p3 = layer4_out_read_reg_2978[32'd281];

assign tmp_205_fu_2228_p3 = add_ln52_30_fu_2218_p2[32'd15];

assign tmp_207_fu_2343_p3 = layer4_out_read_reg_2978[32'd321];

assign tmp_208_fu_2350_p3 = layer4_out_read_reg_2978[32'd320];

assign tmp_210_fu_2382_p3 = add_ln52_31_fu_2372_p2[32'd15];

assign tmp_212_fu_2497_p3 = layer4_out_read_reg_2978[32'd360];

assign tmp_213_fu_2504_p3 = layer4_out_read_reg_2978[32'd359];

assign tmp_215_fu_2536_p3 = add_ln52_32_fu_2526_p2[32'd15];

assign tmp_217_fu_2651_p3 = layer4_out_read_reg_2978[32'd399];

assign tmp_218_fu_2658_p3 = layer4_out_read_reg_2978[32'd398];

assign tmp_220_fu_2690_p3 = add_ln52_33_fu_2680_p2[32'd15];

assign tmp_222_fu_2805_p3 = layer4_out_read_reg_2978[32'd438];

assign tmp_223_fu_2812_p3 = layer4_out_read_reg_2978[32'd437];

assign tmp_225_fu_2844_p3 = add_ln52_34_fu_2834_p2[32'd15];

assign tmp_47_fu_456_p4 = {{layer4_out_dout[46:39]}};

assign tmp_48_fu_480_p4 = {{layer4_out_dout[77:64]}};

assign tmp_49_fu_516_p4 = {{layer4_out_dout[85:78]}};

assign tmp_50_fu_540_p4 = {{layer4_out_dout[116:103]}};

assign tmp_51_fu_576_p4 = {{layer4_out_dout[124:117]}};

assign tmp_52_fu_600_p4 = {{layer4_out_dout[155:142]}};

assign tmp_53_fu_636_p4 = {{layer4_out_dout[163:156]}};

assign tmp_54_fu_660_p4 = {{layer4_out_dout[194:181]}};

assign tmp_55_fu_696_p4 = {{layer4_out_dout[202:195]}};

assign tmp_56_fu_720_p4 = {{layer4_out_dout[233:220]}};

assign tmp_57_fu_756_p4 = {{layer4_out_dout[241:234]}};

assign tmp_58_fu_780_p4 = {{layer4_out_dout[272:259]}};

assign tmp_59_fu_816_p4 = {{layer4_out_dout[280:273]}};

assign tmp_60_fu_840_p4 = {{layer4_out_dout[311:298]}};

assign tmp_61_fu_876_p4 = {{layer4_out_dout[319:312]}};

assign tmp_62_fu_900_p4 = {{layer4_out_dout[350:337]}};

assign tmp_63_fu_936_p4 = {{layer4_out_dout[358:351]}};

assign tmp_64_fu_960_p4 = {{layer4_out_dout[389:376]}};

assign tmp_65_fu_996_p4 = {{layer4_out_dout[397:390]}};

assign tmp_66_fu_1020_p4 = {{layer4_out_dout[428:415]}};

assign tmp_67_fu_1056_p4 = {{layer4_out_dout[436:429]}};

assign tmp_68_fu_1080_p4 = {{layer4_out_dout[467:454]}};

assign tmp_s_fu_420_p4 = {{layer4_out_dout[38:25]}};

assign trunc_ln44_23_fu_288_p4 = {{layer4_out_dout[116:78]}};

assign trunc_ln44_24_fu_298_p4 = {{layer4_out_dout[155:117]}};

assign trunc_ln44_25_fu_308_p4 = {{layer4_out_dout[194:156]}};

assign trunc_ln44_26_fu_318_p4 = {{layer4_out_dout[233:195]}};

assign trunc_ln44_27_fu_328_p4 = {{layer4_out_dout[272:234]}};

assign trunc_ln44_28_fu_338_p4 = {{layer4_out_dout[311:273]}};

assign trunc_ln44_29_fu_348_p4 = {{layer4_out_dout[350:312]}};

assign trunc_ln44_30_fu_358_p4 = {{layer4_out_dout[389:351]}};

assign trunc_ln44_31_fu_368_p4 = {{layer4_out_dout[428:390]}};

assign trunc_ln44_32_fu_378_p4 = {{layer4_out_dout[467:429]}};

assign trunc_ln44_fu_274_p1 = layer4_out_dout[38:0];

assign trunc_ln44_s_fu_278_p4 = {{layer4_out_dout[77:39]}};

assign trunc_ln52_23_fu_1410_p4 = {{layer4_out_read_reg_2978[102:87]}};

assign trunc_ln52_24_fu_1564_p4 = {{layer4_out_read_reg_2978[141:126]}};

assign trunc_ln52_25_fu_1718_p4 = {{layer4_out_read_reg_2978[180:165]}};

assign trunc_ln52_26_fu_1872_p4 = {{layer4_out_read_reg_2978[219:204]}};

assign trunc_ln52_27_fu_2026_p4 = {{layer4_out_read_reg_2978[258:243]}};

assign trunc_ln52_28_fu_2180_p4 = {{layer4_out_read_reg_2978[297:282]}};

assign trunc_ln52_29_fu_2334_p4 = {{layer4_out_read_reg_2978[336:321]}};

assign trunc_ln52_30_fu_2488_p4 = {{layer4_out_read_reg_2978[375:360]}};

assign trunc_ln52_31_fu_2642_p4 = {{layer4_out_read_reg_2978[414:399]}};

assign trunc_ln52_32_fu_2796_p4 = {{layer4_out_read_reg_2978[453:438]}};

assign trunc_ln52_48_fu_1146_p1 = add_ln52_fu_1140_p2[14:0];

assign trunc_ln52_49_fu_1300_p1 = add_ln52_24_fu_1294_p2[14:0];

assign trunc_ln52_50_fu_1454_p1 = add_ln52_25_fu_1448_p2[14:0];

assign trunc_ln52_51_fu_1608_p1 = add_ln52_26_fu_1602_p2[14:0];

assign trunc_ln52_52_fu_1762_p1 = add_ln52_27_fu_1756_p2[14:0];

assign trunc_ln52_53_fu_1916_p1 = add_ln52_28_fu_1910_p2[14:0];

assign trunc_ln52_54_fu_2070_p1 = add_ln52_29_fu_2064_p2[14:0];

assign trunc_ln52_55_fu_2224_p1 = add_ln52_30_fu_2218_p2[14:0];

assign trunc_ln52_56_fu_2378_p1 = add_ln52_31_fu_2372_p2[14:0];

assign trunc_ln52_57_fu_2532_p1 = add_ln52_32_fu_2526_p2[14:0];

assign trunc_ln52_58_fu_2686_p1 = add_ln52_33_fu_2680_p2[14:0];

assign trunc_ln52_59_fu_2840_p1 = add_ln52_34_fu_2834_p2[14:0];

assign trunc_ln52_fu_402_p1 = layer4_out_dout[7:0];

assign trunc_ln52_s_fu_1256_p4 = {{layer4_out_read_reg_2978[63:48]}};

assign trunc_ln5_fu_1102_p4 = {{layer4_out_read_reg_2978[24:9]}};

assign xor_ln52_48_fu_1197_p2 = (1'd1 ^ and_ln52_48_fu_1192_p2);

assign xor_ln52_49_fu_1335_p2 = (or_ln52_75_fu_1330_p2 ^ 1'd1);

assign xor_ln52_50_fu_1351_p2 = (1'd1 ^ and_ln52_50_fu_1346_p2);

assign xor_ln52_51_fu_1489_p2 = (or_ln52_78_fu_1484_p2 ^ 1'd1);

assign xor_ln52_52_fu_1505_p2 = (1'd1 ^ and_ln52_52_fu_1500_p2);

assign xor_ln52_53_fu_1643_p2 = (or_ln52_81_fu_1638_p2 ^ 1'd1);

assign xor_ln52_54_fu_1659_p2 = (1'd1 ^ and_ln52_54_fu_1654_p2);

assign xor_ln52_55_fu_1797_p2 = (or_ln52_84_fu_1792_p2 ^ 1'd1);

assign xor_ln52_56_fu_1813_p2 = (1'd1 ^ and_ln52_56_fu_1808_p2);

assign xor_ln52_57_fu_1951_p2 = (or_ln52_87_fu_1946_p2 ^ 1'd1);

assign xor_ln52_58_fu_1967_p2 = (1'd1 ^ and_ln52_58_fu_1962_p2);

assign xor_ln52_59_fu_2105_p2 = (or_ln52_90_fu_2100_p2 ^ 1'd1);

assign xor_ln52_60_fu_2121_p2 = (1'd1 ^ and_ln52_60_fu_2116_p2);

assign xor_ln52_61_fu_2259_p2 = (or_ln52_93_fu_2254_p2 ^ 1'd1);

assign xor_ln52_62_fu_2275_p2 = (1'd1 ^ and_ln52_62_fu_2270_p2);

assign xor_ln52_63_fu_2413_p2 = (or_ln52_96_fu_2408_p2 ^ 1'd1);

assign xor_ln52_64_fu_2429_p2 = (1'd1 ^ and_ln52_64_fu_2424_p2);

assign xor_ln52_65_fu_2567_p2 = (or_ln52_99_fu_2562_p2 ^ 1'd1);

assign xor_ln52_66_fu_2583_p2 = (1'd1 ^ and_ln52_66_fu_2578_p2);

assign xor_ln52_67_fu_2721_p2 = (or_ln52_102_fu_2716_p2 ^ 1'd1);

assign xor_ln52_68_fu_2737_p2 = (1'd1 ^ and_ln52_68_fu_2732_p2);

assign xor_ln52_69_fu_2875_p2 = (or_ln52_105_fu_2870_p2 ^ 1'd1);

assign xor_ln52_70_fu_2891_p2 = (1'd1 ^ and_ln52_70_fu_2886_p2);

assign xor_ln52_72_fu_1158_p2 = (tmp_170_fu_1150_p3 ^ 1'd1);

assign xor_ln52_73_fu_1312_p2 = (tmp_175_fu_1304_p3 ^ 1'd1);

assign xor_ln52_74_fu_1466_p2 = (tmp_180_fu_1458_p3 ^ 1'd1);

assign xor_ln52_75_fu_1620_p2 = (tmp_185_fu_1612_p3 ^ 1'd1);

assign xor_ln52_76_fu_1774_p2 = (tmp_190_fu_1766_p3 ^ 1'd1);

assign xor_ln52_77_fu_1928_p2 = (tmp_195_fu_1920_p3 ^ 1'd1);

assign xor_ln52_78_fu_2082_p2 = (tmp_200_fu_2074_p3 ^ 1'd1);

assign xor_ln52_79_fu_2236_p2 = (tmp_205_fu_2228_p3 ^ 1'd1);

assign xor_ln52_80_fu_2390_p2 = (tmp_210_fu_2382_p3 ^ 1'd1);

assign xor_ln52_81_fu_2544_p2 = (tmp_215_fu_2536_p3 ^ 1'd1);

assign xor_ln52_82_fu_2698_p2 = (tmp_220_fu_2690_p3 ^ 1'd1);

assign xor_ln52_83_fu_2852_p2 = (tmp_225_fu_2844_p3 ^ 1'd1);

assign xor_ln52_fu_1181_p2 = (or_ln52_72_fu_1176_p2 ^ 1'd1);

assign zext_ln52_24_fu_1290_p1 = and_ln52_49_fu_1284_p2;

assign zext_ln52_25_fu_1444_p1 = and_ln52_51_fu_1438_p2;

assign zext_ln52_26_fu_1598_p1 = and_ln52_53_fu_1592_p2;

assign zext_ln52_27_fu_1752_p1 = and_ln52_55_fu_1746_p2;

assign zext_ln52_28_fu_1906_p1 = and_ln52_57_fu_1900_p2;

assign zext_ln52_29_fu_2060_p1 = and_ln52_59_fu_2054_p2;

assign zext_ln52_30_fu_2214_p1 = and_ln52_61_fu_2208_p2;

assign zext_ln52_31_fu_2368_p1 = and_ln52_63_fu_2362_p2;

assign zext_ln52_32_fu_2522_p1 = and_ln52_65_fu_2516_p2;

assign zext_ln52_33_fu_2676_p1 = and_ln52_67_fu_2670_p2;

assign zext_ln52_34_fu_2830_p1 = and_ln52_69_fu_2824_p2;

assign zext_ln52_48_fu_1211_p1 = select_ln52_96_fu_1203_p3;

assign zext_ln52_49_fu_1365_p1 = select_ln52_100_fu_1357_p3;

assign zext_ln52_50_fu_1519_p1 = select_ln52_104_fu_1511_p3;

assign zext_ln52_51_fu_1673_p1 = select_ln52_108_fu_1665_p3;

assign zext_ln52_52_fu_1827_p1 = select_ln52_112_fu_1819_p3;

assign zext_ln52_53_fu_1981_p1 = select_ln52_116_fu_1973_p3;

assign zext_ln52_54_fu_2135_p1 = select_ln52_120_fu_2127_p3;

assign zext_ln52_55_fu_2289_p1 = select_ln52_124_fu_2281_p3;

assign zext_ln52_56_fu_2443_p1 = select_ln52_128_fu_2435_p3;

assign zext_ln52_57_fu_2597_p1 = select_ln52_132_fu_2589_p3;

assign zext_ln52_58_fu_2751_p1 = select_ln52_136_fu_2743_p3;

assign zext_ln52_59_fu_2905_p1 = select_ln52_140_fu_2897_p3;

assign zext_ln52_fu_1136_p1 = and_ln52_fu_1130_p2;

endmodule //myproject_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_s
