// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_22_13_5_3_0_12u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        in_elem_0_0_0_0_0_val,
        layer2_out_din,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [0:0] in_elem_0_0_0_0_0_val;
output  [263:0] layer2_out_din;
input  [10:0] layer2_out_num_data_valid;
input  [10:0] layer2_out_fifo_cap;
input   layer2_out_full_n;
output   layer2_out_write;
output   layer2_out_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer2_out_write;
reg layer2_out_blk_n;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
reg   [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln284_reg_379;
reg   [0:0] and_ln284_1_reg_383;
wire   [0:0] icmp_ln284_fu_146_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] and_ln284_1_fu_208_p2;
wire   [0:0] icmp_ln303_fu_220_p2;
reg   [0:0] icmp_ln303_reg_387;
wire   [31:0] select_ln313_fu_294_p3;
reg   [21:0] res_out_reg_399;
wire    ap_block_pp0_stage2_11001;
reg   [21:0] res_out_1_reg_404;
reg   [21:0] res_out_2_reg_409;
reg   [21:0] res_out_3_reg_414;
reg   [21:0] res_out_4_reg_419;
reg   [21:0] res_out_5_reg_424;
reg   [21:0] res_out_6_reg_429;
reg   [21:0] res_out_7_reg_434;
reg   [21:0] res_out_8_reg_439;
reg   [21:0] res_out_9_reg_444;
reg   [21:0] res_out_24_reg_449;
reg   [21:0] res_out_25_reg_454;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_predicate_op60_write_state4;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_done;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_idle;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ready;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld;
wire   [0:0] call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
wire    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld;
reg    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce;
reg    ap_block_state4_pp0_stage0_iter1_ignore_call2;
reg    ap_block_pp0_stage0_11001_ignoreCallOp6;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10;
wire   [21:0] grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11;
reg    grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce;
reg    ap_predicate_op22_call_state2;
reg    ap_predicate_op43_call_state3;
wire    ap_block_pp0_stage1_11001_ignoreCallOp22;
wire    ap_block_pp0_stage2_11001_ignoreCallOp43;
reg   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_81;
wire   [0:0] icmp_ln307_fu_270_p2;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire   [31:0] select_ln318_fu_238_p3;
wire   [31:0] add_ln307_fu_264_p2;
wire   [31:0] add_ln303_fu_214_p2;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] tmp_323_fu_170_p4;
wire   [30:0] tmp_324_fu_186_p4;
wire   [0:0] icmp_ln284_4_fu_180_p2;
wire   [0:0] icmp_ln284_5_fu_196_p2;
wire   [0:0] and_ln284_fu_202_p2;
wire   [0:0] icmp_ln284_1_fu_164_p2;
wire   [31:0] add_ln318_fu_232_p2;
wire   [0:0] icmp_ln313_fu_282_p2;
wire   [31:0] add_ln313_fu_288_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
reg    ap_condition_301;
reg    ap_condition_229;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 = 1'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig = 1'd0;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_uint_1_1u_config2_s call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start),
    .ap_done(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_done),
    .ap_idle(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_idle),
    .ap_ready(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld),
    .ap_ce(call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce)
);

myproject_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .ap_return_0(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11),
    .ap_ce(grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_301)) begin
        if ((icmp_ln307_fu_270_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_81 <= 32'd0;
        end else if ((icmp_ln307_fu_270_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_81 <= select_ln313_fu_294_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((icmp_ln303_fu_220_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_220_p2 == 1'd0)) begin
            pX_2 <= add_ln303_fu_214_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_301)) begin
        if ((icmp_ln307_fu_270_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln307_fu_270_p2 == 1'd0)) begin
            pY_2 <= add_ln307_fu_264_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((icmp_ln303_fu_220_p2 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_220_p2 == 1'd0)) begin
            sX_2 <= select_ln318_fu_238_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        and_ln284_1_reg_383 <= and_ln284_1_fu_208_p2;
        icmp_ln284_reg_379 <= icmp_ln284_fu_146_p2;
        icmp_ln303_reg_387 <= icmp_ln303_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        res_out_1_reg_404 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1;
        res_out_24_reg_449 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10;
        res_out_25_reg_454 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11;
        res_out_2_reg_409 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2;
        res_out_3_reg_414 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3;
        res_out_4_reg_419 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4;
        res_out_5_reg_424 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5;
        res_out_6_reg_429 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6;
        res_out_7_reg_434 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7;
        res_out_8_reg_439 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8;
        res_out_9_reg_444 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9;
        res_out_reg_399 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln303_reg_387 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sY_2 <= ap_phi_reg_pp0_iter0_storemerge_reg_81;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp6) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp43) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp22) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln284_1_reg_383) & (icmp_ln284_reg_379 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op60_write_state4 == 1'b1))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln303_fu_214_p2 = (pX_2 + 32'd1);

assign add_ln307_fu_264_p2 = (pY_2 + 32'd1);

assign add_ln313_fu_288_p2 = (sY_2 + 32'd1);

assign add_ln318_fu_232_p2 = (sX_2 + 32'd1);

assign and_ln284_1_fu_208_p2 = (icmp_ln284_1_fu_164_p2 & and_ln284_fu_202_p2);

assign and_ln284_fu_202_p2 = (icmp_ln284_5_fu_196_p2 & icmp_ln284_4_fu_180_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp6 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_ignore_call2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp22 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp43 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op60_write_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1_ignore_call2 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op60_write_state4 == 1'b1));
end

always @ (*) begin
    ap_condition_229 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_301 = ((icmp_ln303_fu_220_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op22_call_state2 = ((icmp_ln284_fu_146_p2 == 1'd1) & (1'd1 == and_ln284_1_fu_208_p2));
end

always @ (*) begin
    ap_predicate_op43_call_state3 = ((1'd1 == and_ln284_1_reg_383) & (icmp_ln284_reg_379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op60_write_state4 = ((1'd1 == and_ln284_1_reg_383) & (icmp_ln284_reg_379 == 1'd1));
end

assign icmp_ln284_1_fu_164_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln284_4_fu_180_p2 = (($signed(tmp_323_fu_170_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_5_fu_196_p2 = (($signed(tmp_324_fu_186_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_146_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_220_p2 = ((add_ln303_fu_214_p2 == 32'd38) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_270_p2 = ((add_ln307_fu_264_p2 == 32'd26) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_282_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign layer2_out_din = {{{{{{{{{{{{res_out_25_reg_454}, {res_out_24_reg_449}}, {res_out_9_reg_444}}, {res_out_8_reg_439}}, {res_out_7_reg_434}}, {res_out_6_reg_429}}, {res_out_5_reg_424}}, {res_out_4_reg_419}}, {res_out_3_reg_414}}, {res_out_2_reg_409}}, {res_out_1_reg_404}}, {res_out_reg_399}};

assign select_ln313_fu_294_p3 = ((icmp_ln313_fu_282_p2[0:0] == 1'b1) ? 32'd2 : add_ln313_fu_288_p2);

assign select_ln318_fu_238_p3 = ((icmp_ln284_fu_146_p2[0:0] == 1'b1) ? 32'd2 : add_ln318_fu_232_p2);

assign tmp_323_fu_170_p4 = {{pY_2[31:1]}};

assign tmp_324_fu_186_p4 = {{pX_2[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_22_13_5_3_0_12u_config2_s
