// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu080-ffvb2104-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.632625,HLS_SYN_LAT=4518,HLS_SYN_TPT=4483,HLS_SYN_MEM=281,HLS_SYN_DSP=0,HLS_SYN_FF=124370,HLS_SYN_LUT=158711,HLS_VERSION=2023_2}" *)

module myproject (
        input_layer_TDATA,
        layer18_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_TVALID,
        input_layer_TREADY,
        ap_start,
        layer18_out_TVALID,
        layer18_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] input_layer_TDATA;
output  [15:0] layer18_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_TVALID;
output   input_layer_TREADY;
input   ap_start;
output   layer18_out_TVALID;
input   layer18_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_start;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_done;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_continue;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_idle;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_ready;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_start_out;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_start_write;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_input_layer_TREADY;
wire   [0:0] zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_din;
wire    zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_write;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer19_out_read;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_start_write;
wire   [263:0] conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_write;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_start;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_done;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_continue;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_idle;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_ready;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer2_out_read;
wire   [467:0] normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_din;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_write;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_start_out;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_start_write;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer4_out_read;
wire   [191:0] relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_din;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_write;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_start_out;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_start;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_done;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer5_out_read;
wire   [191:0] pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_din;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_write;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_start_out;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_start;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_done;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_continue;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_idle;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_ready;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_start_out;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_start_write;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer6_out_read;
wire   [191:0] zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_din;
wire    zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_write;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_start;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_done;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_continue;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_idle;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_ready;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_start_out;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_start_write;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer20_out_read;
wire   [959:0] conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_din;
wire    conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_write;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_start;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_done;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_continue;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_idle;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_ready;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer7_out_read;
wire   [1367:0] normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_din;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_write;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_start_out;
wire    normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_start_write;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_start;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_done;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_continue;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_idle;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_ready;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer9_out_read;
wire   [383:0] relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_din;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_write;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_start_out;
wire    relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_start;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_done;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer10_out_read;
wire   [383:0] pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_din;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_write;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_start_out;
wire    pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_start_write;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_start;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_done;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_continue;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_idle;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_ready;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_start_out;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_start_write;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer11_out_read;
wire   [191:0] dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_din;
wire    dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_write;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_start;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_done;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_continue;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_idle;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_ready;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_start_out;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_start_write;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer13_out_read;
wire   [395:0] normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_din;
wire    normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_write;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_start;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_done;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_continue;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_idle;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_ready;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_start_out;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_start_write;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer15_out_read;
wire   [191:0] relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_din;
wire    relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_write;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_start;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_done;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_continue;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_idle;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_ready;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_start_out;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_start_write;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer16_out_read;
wire   [36:0] dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_din;
wire    dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_write;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_start;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_done;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_continue;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_idle;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_ready;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer17_out_read;
wire   [15:0] sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TDATA;
wire    sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TVALID;
wire    layer19_out_full_n;
wire   [0:0] layer19_out_dout;
wire   [10:0] layer19_out_num_data_valid;
wire   [10:0] layer19_out_fifo_cap;
wire    layer19_out_empty_n;
wire    layer2_out_full_n;
wire   [263:0] layer2_out_dout;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer4_out_full_n;
wire   [467:0] layer4_out_dout;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [191:0] layer5_out_dout;
wire   [10:0] layer5_out_num_data_valid;
wire   [10:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [191:0] layer6_out_dout;
wire   [8:0] layer6_out_num_data_valid;
wire   [8:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer20_out_full_n;
wire   [191:0] layer20_out_dout;
wire   [9:0] layer20_out_num_data_valid;
wire   [9:0] layer20_out_fifo_cap;
wire    layer20_out_empty_n;
wire    layer7_out_full_n;
wire   [959:0] layer7_out_dout;
wire   [8:0] layer7_out_num_data_valid;
wire   [8:0] layer7_out_fifo_cap;
wire    layer7_out_empty_n;
wire    layer9_out_full_n;
wire   [1367:0] layer9_out_dout;
wire   [8:0] layer9_out_num_data_valid;
wire   [8:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire    layer10_out_full_n;
wire   [383:0] layer10_out_dout;
wire   [8:0] layer10_out_num_data_valid;
wire   [8:0] layer10_out_fifo_cap;
wire    layer10_out_empty_n;
wire    layer11_out_full_n;
wire   [383:0] layer11_out_dout;
wire   [6:0] layer11_out_num_data_valid;
wire   [6:0] layer11_out_fifo_cap;
wire    layer11_out_empty_n;
wire    layer13_out_full_n;
wire   [191:0] layer13_out_dout;
wire   [1:0] layer13_out_num_data_valid;
wire   [1:0] layer13_out_fifo_cap;
wire    layer13_out_empty_n;
wire    layer15_out_full_n;
wire   [395:0] layer15_out_dout;
wire   [1:0] layer15_out_num_data_valid;
wire   [1:0] layer15_out_fifo_cap;
wire    layer15_out_empty_n;
wire    layer16_out_full_n;
wire   [191:0] layer16_out_dout;
wire   [1:0] layer16_out_num_data_valid;
wire   [1:0] layer16_out_fifo_cap;
wire    layer16_out_empty_n;
wire    layer17_out_full_n;
wire   [36:0] layer17_out_dout;
wire   [1:0] layer17_out_num_data_valid;
wire   [1:0] layer17_out_fifo_cap;
wire    layer17_out_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_din;
wire    start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_dout;
wire    start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_din;
wire    start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_dout;
wire    start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_din;
wire    start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_dout;
wire    start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_din;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_dout;
wire    start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_din;
wire    start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_dout;
wire    start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_din;
wire    start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_dout;
wire    start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_din;
wire    start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_dout;
wire    start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_din;
wire    start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_dout;
wire    start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_din;
wire    start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_dout;
wire    start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_din;
wire    start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_dout;
wire    start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_din;
wire    start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_dout;
wire    start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_empty_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_din;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_full_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_dout;
wire    start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_empty_n;

myproject_zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_s zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_start_write),
    .input_layer_TDATA(input_layer_TDATA),
    .input_layer_TVALID(input_layer_TVALID),
    .input_layer_TREADY(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_input_layer_TREADY),
    .layer19_out_din(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_din),
    .layer19_out_num_data_valid(layer19_out_num_data_valid),
    .layer19_out_fifo_cap(layer19_out_fifo_cap),
    .layer19_out_full_n(layer19_out_full_n),
    .layer19_out_write(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_write)
);

myproject_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_s conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_ready),
    .layer19_out_dout(layer19_out_dout),
    .layer19_out_num_data_valid(layer19_out_num_data_valid),
    .layer19_out_fifo_cap(layer19_out_fifo_cap),
    .layer19_out_empty_n(layer19_out_empty_n),
    .layer19_out_read(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer19_out_read),
    .start_out(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_start_write),
    .layer2_out_din(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_write)
);

myproject_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_s normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_full_n),
    .ap_done(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer2_out_read),
    .layer4_out_din(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_write),
    .start_out(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_start_out),
    .start_write(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_start_write)
);

myproject_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_s relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_full_n),
    .ap_done(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer4_out_read),
    .layer5_out_din(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_write),
    .start_out(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_start_out),
    .start_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_s pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_ready),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer5_out_read),
    .layer6_out_din(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_write),
    .start_out(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_start_write)
);

myproject_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_s zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_full_n),
    .ap_done(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_ready),
    .start_out(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_start_out),
    .start_write(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_start_write),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer6_out_read),
    .layer20_out_din(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_din),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_full_n(layer20_out_full_n),
    .layer20_out_write(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_write)
);

myproject_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_s conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_full_n),
    .ap_done(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_done),
    .ap_continue(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_ready),
    .start_out(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_start_out),
    .start_write(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_start_write),
    .layer20_out_dout(layer20_out_dout),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_empty_n(layer20_out_empty_n),
    .layer20_out_read(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer20_out_read),
    .layer7_out_din(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_din),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_write)
);

myproject_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_s normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_full_n),
    .ap_done(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_ready),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer7_out_read),
    .layer9_out_din(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_write),
    .start_out(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_start_out),
    .start_write(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_start_write)
);

myproject_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_s relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_full_n),
    .ap_done(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_ready),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer9_out_read),
    .layer10_out_din(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_din),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_write),
    .start_out(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_start_out),
    .start_write(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_s pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_ready),
    .layer10_out_dout(layer10_out_dout),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_empty_n(layer10_out_empty_n),
    .layer10_out_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer10_out_read),
    .layer11_out_din(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_din),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_write),
    .start_out(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_start_write)
);

myproject_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_s dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_full_n),
    .ap_done(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_ready),
    .start_out(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_start_out),
    .start_write(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_start_write),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer11_out_read),
    .layer13_out_din(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_din),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_write)
);

myproject_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_s normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_full_n),
    .ap_done(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_start_out),
    .start_write(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_start_write),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer13_out_read),
    .layer15_out_din(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_din),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_full_n(layer15_out_full_n),
    .layer15_out_write(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_write)
);

myproject_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_s relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_full_n),
    .ap_done(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_ready),
    .start_out(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_start_out),
    .start_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_start_write),
    .layer15_out_dout(layer15_out_dout),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer15_out_empty_n(layer15_out_empty_n),
    .layer15_out_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer15_out_read),
    .layer16_out_din(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_din),
    .layer16_out_num_data_valid(layer16_out_num_data_valid),
    .layer16_out_fifo_cap(layer16_out_fifo_cap),
    .layer16_out_full_n(layer16_out_full_n),
    .layer16_out_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_write)
);

myproject_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_s dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_start),
    .start_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_full_n),
    .ap_done(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_ready),
    .start_out(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_start_out),
    .start_write(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_start_write),
    .layer16_out_dout(layer16_out_dout),
    .layer16_out_num_data_valid(layer16_out_num_data_valid),
    .layer16_out_fifo_cap(layer16_out_fifo_cap),
    .layer16_out_empty_n(layer16_out_empty_n),
    .layer16_out_read(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer16_out_read),
    .layer17_out_din(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_din),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_write)
);

myproject_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_s sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_start),
    .ap_done(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_done),
    .ap_continue(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_continue),
    .ap_idle(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_idle),
    .ap_ready(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_ready),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer17_out_read),
    .layer18_out_TDATA(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TDATA),
    .layer18_out_TVALID(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TVALID),
    .layer18_out_TREADY(layer18_out_TREADY)
);

myproject_fifo_w1_d988_S layer19_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_din),
    .if_full_n(layer19_out_full_n),
    .if_write(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_layer19_out_write),
    .if_dout(layer19_out_dout),
    .if_num_data_valid(layer19_out_num_data_valid),
    .if_fifo_cap(layer19_out_fifo_cap),
    .if_empty_n(layer19_out_empty_n),
    .if_read(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer19_out_read)
);

myproject_fifo_w264_d864_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer2_out_read)
);

myproject_fifo_w468_d864_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer4_out_read)
);

myproject_fifo_w192_d864_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer5_out_read)
);

myproject_fifo_w192_d216_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer6_out_read)
);

myproject_fifo_w192_d280_A layer20_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_din),
    .if_full_n(layer20_out_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_layer20_out_write),
    .if_dout(layer20_out_dout),
    .if_num_data_valid(layer20_out_num_data_valid),
    .if_fifo_cap(layer20_out_fifo_cap),
    .if_empty_n(layer20_out_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer20_out_read)
);

myproject_fifo_w960_d216_A layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap),
    .if_empty_n(layer7_out_empty_n),
    .if_read(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer7_out_read)
);

myproject_fifo_w1368_d216_A layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer9_out_read)
);

myproject_fifo_w384_d216_A layer10_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_din),
    .if_full_n(layer10_out_full_n),
    .if_write(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_layer10_out_write),
    .if_dout(layer10_out_dout),
    .if_num_data_valid(layer10_out_num_data_valid),
    .if_fifo_cap(layer10_out_fifo_cap),
    .if_empty_n(layer10_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer10_out_read)
);

myproject_fifo_w384_d54_A layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap),
    .if_empty_n(layer11_out_empty_n),
    .if_read(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer11_out_read)
);

myproject_fifo_w192_d1_S layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap),
    .if_empty_n(layer13_out_empty_n),
    .if_read(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer13_out_read)
);

myproject_fifo_w396_d1_S layer15_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_din),
    .if_full_n(layer15_out_full_n),
    .if_write(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_layer15_out_write),
    .if_dout(layer15_out_dout),
    .if_num_data_valid(layer15_out_num_data_valid),
    .if_fifo_cap(layer15_out_fifo_cap),
    .if_empty_n(layer15_out_empty_n),
    .if_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer15_out_read)
);

myproject_fifo_w192_d1_S layer16_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_din),
    .if_full_n(layer16_out_full_n),
    .if_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_layer16_out_write),
    .if_dout(layer16_out_dout),
    .if_num_data_valid(layer16_out_num_data_valid),
    .if_fifo_cap(layer16_out_fifo_cap),
    .if_empty_n(layer16_out_empty_n),
    .if_read(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer16_out_read)
);

myproject_fifo_w37_d1_S layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap),
    .if_empty_n(layer17_out_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer17_out_read)
);

myproject_start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0 start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4bdk start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4bdk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_empty_n),
    .if_read(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5bek start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5bek_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_full_n),
    .if_write(normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_empty_n),
    .if_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0 start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_full_n),
    .if_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_ready)
);

myproject_start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0 start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_empty_n),
    .if_read(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0 start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_full_n),
    .if_write(zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9bfk start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9bfk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_full_n),
    .if_write(conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_empty_n),
    .if_read(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config1bgk start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config1bgk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_full_n),
    .if_write(normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_empty_n),
    .if_read(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0 start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_full_n),
    .if_write(relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0 start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_empty_n),
    .if_read(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config1bhl start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config1bhl_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_full_n),
    .if_write(dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_empty_n),
    .if_read(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config1bil start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config1bil_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_full_n),
    .if_write(normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_empty_n),
    .if_read(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0 start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_full_n),
    .if_write(relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_empty_n),
    .if_read(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_ready)
);

myproject_start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0 start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_din),
    .if_full_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_full_n),
    .if_write(dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_start_write),
    .if_dout(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_dout),
    .if_empty_n(start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_ready)
);

assign ap_done = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_done;

assign ap_idle = (zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_idle & zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_idle & sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_idle & relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_idle & relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_idle & relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_idle & pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_idle & pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_idle & normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_idle & normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_idle & normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_idle & dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_idle & dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_idle & conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_idle 
    & conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_idle);

assign ap_ready = zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_ap_start = start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_empty_n;

assign conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_ap_start = start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_empty_n;

assign dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_ap_start = start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_empty_n;

assign dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_ap_start = start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_empty_n;

assign input_layer_TREADY = zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_input_layer_TREADY;

assign layer18_out_TDATA = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TDATA;

assign layer18_out_TVALID = sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_layer18_out_TVALID;

assign normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_ap_start = start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_empty_n;

assign normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_ap_start = start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_empty_n;

assign normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_ap_start = start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_empty_n;

assign pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_ap_start = start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_empty_n;

assign pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_ap_start = start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_empty_n;

assign relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_ap_start = start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_empty_n;

assign relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_ap_start = start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_empty_n;

assign relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_ap_start = start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_empty_n;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_continue = 1'b1;

assign sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_ap_start = start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_uint_1u_array_ap_fixed_22_13_5_3_0_12u_config2_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_array_ap_fixed_40_21_5_3_0_24u_config7_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_12u_array_ap_fixed_37_18_5_3_0_1u_config17_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_24u_array_ap_fixed_16_6_5_3_0_12u_config13_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config6_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_ufixed_16_6_4_0_0_24u_config11_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config16_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_12u_array_ap_ufixed_16_6_4_0_0_12u_relu_config5_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_24u_array_ap_ufixed_16_6_4_0_0_24u_relu_config10_U0_din = 1'b1;

assign start_for_sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config18_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_din = 1'b1;

assign zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_uint_1_1u_array_ap_uint_1_1u_config19_U0_ap_start = ap_start;

assign zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_ap_start = start_for_zeropad2d_cl_array_array_ap_ufixed_16_6_4_0_0_12u_config20_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "myproject_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myproject

