// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer7_out_dout,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer7_out_empty_n,
        layer7_out_read,
        layer9_out_din,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_full_n,
        layer9_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [959:0] layer7_out_dout;
input  [8:0] layer7_out_num_data_valid;
input  [8:0] layer7_out_fifo_cap;
input   layer7_out_empty_n;
output   layer7_out_read;
output  [1367:0] layer9_out_din;
input  [8:0] layer9_out_num_data_valid;
input  [8:0] layer9_out_fifo_cap;
input   layer9_out_full_n;
output   layer9_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer7_out_read;
reg layer9_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_441057_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer7_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [39:0] a_fu_441074_p1;
reg  signed [39:0] a_reg_441768;
reg  signed [39:0] a_1_reg_441773;
reg  signed [39:0] a_2_reg_441778;
reg  signed [39:0] a_3_reg_441783;
reg  signed [39:0] a_4_reg_441788;
reg  signed [39:0] a_5_reg_441793;
reg  signed [39:0] a_6_reg_441798;
reg  signed [39:0] a_7_reg_441803;
reg  signed [39:0] a_8_reg_441808;
reg  signed [39:0] a_9_reg_441813;
reg  signed [39:0] a_20_reg_441818;
reg  signed [39:0] a_10_reg_441823;
reg  signed [39:0] a_11_reg_441828;
reg  signed [39:0] a_12_reg_441833;
reg  signed [39:0] a_13_reg_441838;
reg  signed [39:0] a_14_reg_441843;
reg  signed [39:0] a_15_reg_441848;
reg  signed [39:0] a_16_reg_441853;
reg  signed [39:0] a_17_reg_441858;
reg  signed [39:0] a_18_reg_441863;
reg  signed [39:0] a_19_reg_441868;
reg   [39:0] tmp_reg_441873;
reg   [39:0] tmp_reg_441873_pp0_iter2_reg;
reg   [39:0] tmp_reg_441873_pp0_iter3_reg;
reg   [39:0] tmp_2_reg_441879;
reg   [39:0] tmp_2_reg_441879_pp0_iter2_reg;
reg   [39:0] tmp_2_reg_441879_pp0_iter3_reg;
reg   [39:0] tmp_4_reg_441885;
reg   [39:0] tmp_4_reg_441885_pp0_iter2_reg;
reg   [39:0] tmp_4_reg_441885_pp0_iter3_reg;
wire   [50:0] grp_fu_5174_p2;
reg   [50:0] mul_ln73_reg_441996;
wire   [46:0] grp_fu_973_p2;
reg   [46:0] mul_ln42_reg_442001;
wire   [49:0] grp_fu_2667_p2;
reg   [49:0] mul_ln42_1_reg_442006;
wire   [49:0] grp_fu_3792_p2;
reg   [49:0] mul_ln42_2_reg_442011;
wire   [45:0] grp_fu_3116_p2;
reg   [45:0] mul_ln42_3_reg_442016;
wire   [50:0] grp_fu_4712_p2;
reg   [50:0] mul_ln73_1_reg_442021;
wire   [49:0] grp_fu_4886_p2;
reg   [49:0] mul_ln42_4_reg_442026;
wire   [48:0] grp_fu_1734_p2;
reg   [48:0] mul_ln42_5_reg_442031;
wire   [47:0] grp_fu_912_p2;
reg   [47:0] mul_ln42_6_reg_442036;
wire   [48:0] grp_fu_3838_p2;
reg   [48:0] mul_ln42_7_reg_442041;
wire   [48:0] grp_fu_660_p2;
reg   [48:0] mul_ln42_8_reg_442046;
wire   [49:0] grp_fu_3047_p2;
reg   [49:0] mul_ln42_9_reg_442051;
wire   [48:0] grp_fu_5110_p2;
reg   [48:0] mul_ln42_10_reg_442056;
wire   [46:0] grp_fu_3109_p2;
reg   [46:0] mul_ln42_11_reg_442061;
wire   [48:0] grp_fu_2313_p2;
reg   [48:0] mul_ln42_12_reg_442066;
wire   [47:0] grp_fu_2314_p2;
reg   [47:0] mul_ln42_13_reg_442071;
wire   [49:0] grp_fu_2721_p2;
reg   [49:0] mul_ln42_14_reg_442076;
wire   [50:0] grp_fu_4514_p2;
reg   [50:0] mul_ln73_2_reg_442081;
wire   [45:0] add_ln42_18_fu_441424_p2;
reg   [45:0] add_ln42_18_reg_442086;
wire   [47:0] add_ln42_19_fu_441462_p2;
reg   [47:0] add_ln42_19_reg_442091;
wire   [45:0] add_ln42_20_fu_441500_p2;
reg   [45:0] add_ln42_20_reg_442096;
wire   [48:0] grp_fu_5108_p2;
reg   [48:0] mul_ln42_15_reg_442101;
wire   [47:0] grp_fu_3138_p2;
reg   [47:0] mul_ln42_16_reg_442106;
wire   [47:0] grp_fu_521_p2;
reg   [47:0] mul_ln42_17_reg_442111;
reg   [7:0] i_02_fu_244;
wire   [7:0] i_9_fu_441063_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] grp_fu_521_p1;
wire   [9:0] grp_fu_660_p1;
wire   [8:0] grp_fu_912_p1;
wire   [7:0] grp_fu_973_p1;
wire   [9:0] grp_fu_1734_p1;
wire   [9:0] grp_fu_2313_p1;
wire   [8:0] grp_fu_2314_p1;
wire   [10:0] grp_fu_2667_p1;
wire   [10:0] grp_fu_2721_p1;
wire   [10:0] grp_fu_3047_p1;
wire   [7:0] grp_fu_3109_p1;
wire   [6:0] grp_fu_3116_p1;
wire   [8:0] grp_fu_3138_p1;
wire   [10:0] grp_fu_3792_p1;
wire   [9:0] grp_fu_3838_p1;
wire   [11:0] grp_fu_4514_p1;
wire   [11:0] grp_fu_4712_p1;
wire   [10:0] grp_fu_4886_p1;
wire   [9:0] grp_fu_5108_p1;
wire   [9:0] grp_fu_5110_p1;
wire   [11:0] grp_fu_5174_p1;
wire   [44:0] and_ln_fu_441392_p3;
wire   [40:0] and_ln73_1_fu_441403_p3;
wire  signed [41:0] sext_ln42_21_fu_441410_p1;
wire   [41:0] add_ln42_24_fu_441414_p2;
wire  signed [45:0] sext_ln42_22_fu_441420_p1;
wire  signed [45:0] sext_ln73_3_fu_441399_p1;
wire   [46:0] and_ln73_2_fu_441430_p3;
wire   [44:0] and_ln73_3_fu_441441_p3;
wire  signed [45:0] sext_ln42_23_fu_441448_p1;
wire   [45:0] add_ln42_25_fu_441452_p2;
wire  signed [47:0] sext_ln42_24_fu_441458_p1;
wire  signed [47:0] sext_ln73_4_fu_441437_p1;
wire   [44:0] and_ln73_4_fu_441468_p3;
wire   [41:0] and_ln73_5_fu_441479_p3;
wire  signed [42:0] sext_ln42_25_fu_441486_p1;
wire   [42:0] add_ln42_26_fu_441490_p2;
wire  signed [45:0] sext_ln42_26_fu_441496_p1;
wire  signed [45:0] sext_ln73_5_fu_441475_p1;
wire   [50:0] add_ln42_fu_441506_p2;
wire   [46:0] add_ln42_1_fu_441515_p2;
wire   [49:0] add_ln42_2_fu_441524_p2;
wire   [49:0] add_ln42_3_fu_441533_p2;
wire   [45:0] add_ln42_4_fu_441542_p2;
wire   [50:0] add_ln42_5_fu_441551_p2;
wire   [49:0] add_ln42_6_fu_441560_p2;
wire   [48:0] add_ln42_7_fu_441569_p2;
wire   [47:0] add_ln42_8_fu_441578_p2;
wire   [48:0] add_ln42_9_fu_441587_p2;
wire   [48:0] add_ln42_10_fu_441596_p2;
wire   [49:0] add_ln42_11_fu_441605_p2;
wire   [48:0] add_ln42_12_fu_441614_p2;
wire   [46:0] add_ln42_13_fu_441623_p2;
wire   [48:0] add_ln42_14_fu_441632_p2;
wire   [47:0] add_ln42_15_fu_441641_p2;
wire   [49:0] add_ln42_16_fu_441650_p2;
wire   [50:0] add_ln42_17_fu_441659_p2;
wire   [48:0] add_ln42_21_fu_441677_p2;
wire   [47:0] add_ln42_22_fu_441686_p2;
wire   [47:0] add_ln42_23_fu_441695_p2;
wire  signed [56:0] sext_ln70_19_fu_441691_p1;
wire  signed [56:0] sext_ln70_18_fu_441682_p1;
wire  signed [56:0] sext_ln42_17_fu_441674_p1;
wire  signed [56:0] sext_ln42_16_fu_441671_p1;
wire  signed [56:0] sext_ln42_15_fu_441668_p1;
wire  signed [56:0] sext_ln70_17_fu_441664_p1;
wire  signed [56:0] sext_ln70_16_fu_441655_p1;
wire  signed [56:0] sext_ln70_15_fu_441646_p1;
wire  signed [56:0] sext_ln70_14_fu_441637_p1;
wire  signed [56:0] sext_ln70_13_fu_441628_p1;
wire  signed [56:0] sext_ln70_12_fu_441619_p1;
wire  signed [56:0] sext_ln70_11_fu_441610_p1;
wire  signed [56:0] sext_ln70_10_fu_441601_p1;
wire  signed [56:0] sext_ln70_9_fu_441592_p1;
wire  signed [56:0] sext_ln70_8_fu_441583_p1;
wire  signed [56:0] sext_ln70_7_fu_441574_p1;
wire  signed [56:0] sext_ln70_6_fu_441565_p1;
wire  signed [56:0] sext_ln70_5_fu_441556_p1;
wire  signed [56:0] sext_ln70_4_fu_441547_p1;
wire  signed [56:0] sext_ln70_3_fu_441538_p1;
wire  signed [56:0] sext_ln70_2_fu_441529_p1;
wire  signed [56:0] sext_ln70_1_fu_441520_p1;
wire  signed [56:0] sext_ln70_fu_441511_p1;
wire   [1358:0] or_ln46_s_fu_441700_p25;
reg    grp_fu_521_ce;
reg    grp_fu_660_ce;
reg    grp_fu_912_ce;
reg    grp_fu_973_ce;
reg    grp_fu_1734_ce;
reg    grp_fu_2313_ce;
reg    grp_fu_2314_ce;
reg    grp_fu_2667_ce;
reg    grp_fu_2721_ce;
reg    grp_fu_3047_ce;
reg    grp_fu_3109_ce;
reg    grp_fu_3116_ce;
reg    grp_fu_3138_ce;
reg    grp_fu_3792_ce;
reg    grp_fu_3838_ce;
reg    grp_fu_4514_ce;
reg    grp_fu_4712_ce;
reg    grp_fu_4886_ce;
reg    grp_fu_5108_ce;
reg    grp_fu_5110_ce;
reg    grp_fu_5174_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_315;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_02_fu_244 = 8'd0;
end

myproject_mul_40s_9ns_48_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 48 ))
mul_40s_9ns_48_3_1_U523(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_19_reg_441868),
    .din1(grp_fu_521_p1),
    .ce(grp_fu_521_ce),
    .dout(grp_fu_521_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U524(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_20_reg_441818),
    .din1(grp_fu_660_p1),
    .ce(grp_fu_660_ce),
    .dout(grp_fu_660_p2)
);

myproject_mul_40s_9ns_48_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 48 ))
mul_40s_9ns_48_3_1_U525(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_8_reg_441808),
    .din1(grp_fu_912_p1),
    .ce(grp_fu_912_ce),
    .dout(grp_fu_912_p2)
);

myproject_mul_40s_8ns_47_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 47 ))
mul_40s_8ns_47_3_1_U526(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_1_reg_441773),
    .din1(grp_fu_973_p1),
    .ce(grp_fu_973_ce),
    .dout(grp_fu_973_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U527(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_7_reg_441803),
    .din1(grp_fu_1734_p1),
    .ce(grp_fu_1734_ce),
    .dout(grp_fu_1734_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U528(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_13_reg_441838),
    .din1(grp_fu_2313_p1),
    .ce(grp_fu_2313_ce),
    .dout(grp_fu_2313_p2)
);

myproject_mul_40s_9ns_48_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 48 ))
mul_40s_9ns_48_3_1_U529(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_14_reg_441843),
    .din1(grp_fu_2314_p1),
    .ce(grp_fu_2314_ce),
    .dout(grp_fu_2314_p2)
);

myproject_mul_40s_11ns_50_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 50 ))
mul_40s_11ns_50_3_1_U530(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_2_reg_441778),
    .din1(grp_fu_2667_p1),
    .ce(grp_fu_2667_ce),
    .dout(grp_fu_2667_p2)
);

myproject_mul_40s_11ns_50_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 50 ))
mul_40s_11ns_50_3_1_U531(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_15_reg_441848),
    .din1(grp_fu_2721_p1),
    .ce(grp_fu_2721_ce),
    .dout(grp_fu_2721_p2)
);

myproject_mul_40s_11ns_50_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 50 ))
mul_40s_11ns_50_3_1_U532(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_10_reg_441823),
    .din1(grp_fu_3047_p1),
    .ce(grp_fu_3047_ce),
    .dout(grp_fu_3047_p2)
);

myproject_mul_40s_8ns_47_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 47 ))
mul_40s_8ns_47_3_1_U533(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_12_reg_441833),
    .din1(grp_fu_3109_p1),
    .ce(grp_fu_3109_ce),
    .dout(grp_fu_3109_p2)
);

myproject_mul_40s_7ns_46_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 46 ))
mul_40s_7ns_46_3_1_U534(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_4_reg_441788),
    .din1(grp_fu_3116_p1),
    .ce(grp_fu_3116_ce),
    .dout(grp_fu_3116_p2)
);

myproject_mul_40s_9ns_48_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 48 ))
mul_40s_9ns_48_3_1_U535(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_18_reg_441863),
    .din1(grp_fu_3138_p1),
    .ce(grp_fu_3138_ce),
    .dout(grp_fu_3138_p2)
);

myproject_mul_40s_11ns_50_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 50 ))
mul_40s_11ns_50_3_1_U536(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_3_reg_441783),
    .din1(grp_fu_3792_p1),
    .ce(grp_fu_3792_ce),
    .dout(grp_fu_3792_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U537(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_9_reg_441813),
    .din1(grp_fu_3838_p1),
    .ce(grp_fu_3838_ce),
    .dout(grp_fu_3838_p2)
);

myproject_mul_40s_12ns_51_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 51 ))
mul_40s_12ns_51_3_1_U538(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_16_reg_441853),
    .din1(grp_fu_4514_p1),
    .ce(grp_fu_4514_ce),
    .dout(grp_fu_4514_p2)
);

myproject_mul_40s_12ns_51_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 51 ))
mul_40s_12ns_51_3_1_U539(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_5_reg_441793),
    .din1(grp_fu_4712_p1),
    .ce(grp_fu_4712_ce),
    .dout(grp_fu_4712_p2)
);

myproject_mul_40s_11ns_50_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 50 ))
mul_40s_11ns_50_3_1_U540(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_6_reg_441798),
    .din1(grp_fu_4886_p1),
    .ce(grp_fu_4886_ce),
    .dout(grp_fu_4886_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U541(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_17_reg_441858),
    .din1(grp_fu_5108_p1),
    .ce(grp_fu_5108_ce),
    .dout(grp_fu_5108_p2)
);

myproject_mul_40s_10ns_49_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 49 ))
mul_40s_10ns_49_3_1_U542(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_11_reg_441828),
    .din1(grp_fu_5110_p1),
    .ce(grp_fu_5110_ce),
    .dout(grp_fu_5110_p2)
);

myproject_mul_40s_12ns_51_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 51 ))
mul_40s_12ns_51_3_1_U543(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_reg_441768),
    .din1(grp_fu_5174_p1),
    .ce(grp_fu_5174_ce),
    .dout(grp_fu_5174_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_315)) begin
        if ((icmp_ln25_fu_441057_p2 == 1'd0)) begin
            i_02_fu_244 <= i_9_fu_441063_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_02_fu_244 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_10_reg_441823 <= {{layer7_out_dout[479:440]}};
        a_11_reg_441828 <= {{layer7_out_dout[519:480]}};
        a_12_reg_441833 <= {{layer7_out_dout[559:520]}};
        a_13_reg_441838 <= {{layer7_out_dout[599:560]}};
        a_14_reg_441843 <= {{layer7_out_dout[639:600]}};
        a_15_reg_441848 <= {{layer7_out_dout[679:640]}};
        a_16_reg_441853 <= {{layer7_out_dout[719:680]}};
        a_17_reg_441858 <= {{layer7_out_dout[879:840]}};
        a_18_reg_441863 <= {{layer7_out_dout[919:880]}};
        a_19_reg_441868 <= {{layer7_out_dout[959:920]}};
        a_1_reg_441773 <= {{layer7_out_dout[79:40]}};
        a_20_reg_441818 <= {{layer7_out_dout[439:400]}};
        a_2_reg_441778 <= {{layer7_out_dout[119:80]}};
        a_3_reg_441783 <= {{layer7_out_dout[159:120]}};
        a_4_reg_441788 <= {{layer7_out_dout[199:160]}};
        a_5_reg_441793 <= {{layer7_out_dout[239:200]}};
        a_6_reg_441798 <= {{layer7_out_dout[279:240]}};
        a_7_reg_441803 <= {{layer7_out_dout[319:280]}};
        a_8_reg_441808 <= {{layer7_out_dout[359:320]}};
        a_9_reg_441813 <= {{layer7_out_dout[399:360]}};
        a_reg_441768 <= a_fu_441074_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_2_reg_441879 <= {{layer7_out_dout[799:760]}};
        tmp_4_reg_441885 <= {{layer7_out_dout[839:800]}};
        tmp_reg_441873 <= {{layer7_out_dout[759:720]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln42_18_reg_442086[45 : 1] <= add_ln42_18_fu_441424_p2[45 : 1];
        add_ln42_19_reg_442091[47 : 5] <= add_ln42_19_fu_441462_p2[47 : 5];
        add_ln42_20_reg_442096[45 : 2] <= add_ln42_20_fu_441500_p2[45 : 2];
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        mul_ln42_10_reg_442056 <= grp_fu_5110_p2;
        mul_ln42_11_reg_442061 <= grp_fu_3109_p2;
        mul_ln42_12_reg_442066 <= grp_fu_2313_p2;
        mul_ln42_13_reg_442071 <= grp_fu_2314_p2;
        mul_ln42_14_reg_442076 <= grp_fu_2721_p2;
        mul_ln42_15_reg_442101 <= grp_fu_5108_p2;
        mul_ln42_16_reg_442106 <= grp_fu_3138_p2;
        mul_ln42_17_reg_442111 <= grp_fu_521_p2;
        mul_ln42_1_reg_442006 <= grp_fu_2667_p2;
        mul_ln42_2_reg_442011 <= grp_fu_3792_p2;
        mul_ln42_3_reg_442016 <= grp_fu_3116_p2;
        mul_ln42_4_reg_442026 <= grp_fu_4886_p2;
        mul_ln42_5_reg_442031 <= grp_fu_1734_p2;
        mul_ln42_6_reg_442036 <= grp_fu_912_p2;
        mul_ln42_7_reg_442041 <= grp_fu_3838_p2;
        mul_ln42_8_reg_442046 <= grp_fu_660_p2;
        mul_ln42_9_reg_442051 <= grp_fu_3047_p2;
        mul_ln42_reg_442001 <= grp_fu_973_p2;
        mul_ln73_1_reg_442021 <= grp_fu_4712_p2;
        mul_ln73_2_reg_442081 <= grp_fu_4514_p2;
        mul_ln73_reg_441996 <= grp_fu_5174_p2;
        tmp_2_reg_441879_pp0_iter2_reg <= tmp_2_reg_441879;
        tmp_2_reg_441879_pp0_iter3_reg <= tmp_2_reg_441879_pp0_iter2_reg;
        tmp_4_reg_441885_pp0_iter2_reg <= tmp_4_reg_441885;
        tmp_4_reg_441885_pp0_iter3_reg <= tmp_4_reg_441885_pp0_iter2_reg;
        tmp_reg_441873_pp0_iter2_reg <= tmp_reg_441873;
        tmp_reg_441873_pp0_iter3_reg <= tmp_reg_441873_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_441057_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 8'd0;
    end else begin
        ap_sig_allocacmp_i = i_02_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1734_ce = 1'b1;
    end else begin
        grp_fu_1734_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2313_ce = 1'b1;
    end else begin
        grp_fu_2313_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2314_ce = 1'b1;
    end else begin
        grp_fu_2314_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2667_ce = 1'b1;
    end else begin
        grp_fu_2667_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2721_ce = 1'b1;
    end else begin
        grp_fu_2721_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3047_ce = 1'b1;
    end else begin
        grp_fu_3047_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3109_ce = 1'b1;
    end else begin
        grp_fu_3109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3116_ce = 1'b1;
    end else begin
        grp_fu_3116_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3138_ce = 1'b1;
    end else begin
        grp_fu_3138_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3792_ce = 1'b1;
    end else begin
        grp_fu_3792_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3838_ce = 1'b1;
    end else begin
        grp_fu_3838_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_4514_ce = 1'b1;
    end else begin
        grp_fu_4514_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_4712_ce = 1'b1;
    end else begin
        grp_fu_4712_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_4886_ce = 1'b1;
    end else begin
        grp_fu_4886_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_5108_ce = 1'b1;
    end else begin
        grp_fu_5108_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_5110_ce = 1'b1;
    end else begin
        grp_fu_5110_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_5174_ce = 1'b1;
    end else begin
        grp_fu_5174_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_521_ce = 1'b1;
    end else begin
        grp_fu_521_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_660_ce = 1'b1;
    end else begin
        grp_fu_660_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_912_ce = 1'b1;
    end else begin
        grp_fu_912_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_973_ce = 1'b1;
    end else begin
        grp_fu_973_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_441074_p1 = layer7_out_dout[39:0];

assign add_ln42_10_fu_441596_p2 = ($signed(mul_ln42_8_reg_442046) + $signed(49'd562949668208640));

assign add_ln42_11_fu_441605_p2 = ($signed(mul_ln42_9_reg_442051) + $signed(50'd1125898390077440));

assign add_ln42_12_fu_441614_p2 = (mul_ln42_10_reg_442056 + 49'd70254592);

assign add_ln42_13_fu_441623_p2 = ($signed(mul_ln42_11_reg_442061) + $signed(47'd140737133936640));

assign add_ln42_14_fu_441632_p2 = (mul_ln42_12_reg_442066 + 49'd2162163712);

assign add_ln42_15_fu_441641_p2 = ($signed(mul_ln42_13_reg_442071) + $signed(48'd281474887057408));

assign add_ln42_16_fu_441650_p2 = ($signed(mul_ln42_14_reg_442076) + $signed(50'd1125899372068864));

assign add_ln42_17_fu_441659_p2 = ($signed(mul_ln73_2_reg_442081) + $signed(51'd2251799747100672));

assign add_ln42_18_fu_441424_p2 = ($signed(sext_ln42_22_fu_441420_p1) + $signed(sext_ln73_3_fu_441399_p1));

assign add_ln42_19_fu_441462_p2 = ($signed(sext_ln42_24_fu_441458_p1) + $signed(sext_ln73_4_fu_441437_p1));

assign add_ln42_1_fu_441515_p2 = ($signed(mul_ln42_reg_442001) + $signed(47'd140737129218048));

assign add_ln42_20_fu_441500_p2 = ($signed(sext_ln42_26_fu_441496_p1) + $signed(sext_ln73_5_fu_441475_p1));

assign add_ln42_21_fu_441677_p2 = ($signed(mul_ln42_15_reg_442101) + $signed(49'd562949610012672));

assign add_ln42_22_fu_441686_p2 = (mul_ln42_16_reg_442106 + 48'd108527616);

assign add_ln42_23_fu_441695_p2 = (mul_ln42_17_reg_442111 + 48'd111673344);

assign add_ln42_24_fu_441414_p2 = ($signed(sext_ln42_21_fu_441410_p1) + $signed(42'd4397510164480));

assign add_ln42_25_fu_441452_p2 = ($signed(sext_ln42_23_fu_441448_p1) + $signed(46'd70368014893056));

assign add_ln42_26_fu_441490_p2 = ($signed(sext_ln42_25_fu_441486_p1) + $signed(43'd8795602812928));

assign add_ln42_2_fu_441524_p2 = ($signed(mul_ln42_1_reg_442006) + $signed(50'd1125899302338560));

assign add_ln42_3_fu_441533_p2 = (mul_ln42_2_reg_442011 + 50'd571998208);

assign add_ln42_4_fu_441542_p2 = ($signed(mul_ln42_3_reg_442016) + $signed(46'd70368129187840));

assign add_ln42_5_fu_441551_p2 = ($signed(mul_ln73_1_reg_442021) + $signed(51'd2251799113236480));

assign add_ln42_6_fu_441560_p2 = ($signed(mul_ln42_4_reg_442026) + $signed(50'd1125899390943232));

assign add_ln42_7_fu_441569_p2 = ($signed(mul_ln42_5_reg_442031) + $signed(49'd562949239341056));

assign add_ln42_8_fu_441578_p2 = ($signed(mul_ln42_6_reg_442036) + $signed(48'd281474637496320));

assign add_ln42_9_fu_441587_p2 = ($signed(mul_ln42_7_reg_442041) + $signed(49'd562949844369408));

assign add_ln42_fu_441506_p2 = ($signed(mul_ln73_reg_441996) + $signed(51'd2251799039311872));

assign and_ln73_1_fu_441403_p3 = {{tmp_reg_441873_pp0_iter3_reg}, {1'd0}};

assign and_ln73_2_fu_441430_p3 = {{tmp_2_reg_441879_pp0_iter3_reg}, {7'd0}};

assign and_ln73_3_fu_441441_p3 = {{tmp_2_reg_441879_pp0_iter3_reg}, {5'd0}};

assign and_ln73_4_fu_441468_p3 = {{tmp_4_reg_441885_pp0_iter3_reg}, {5'd0}};

assign and_ln73_5_fu_441479_p3 = {{tmp_4_reg_441885_pp0_iter3_reg}, {2'd0}};

assign and_ln_fu_441392_p3 = {{tmp_reg_441873_pp0_iter3_reg}, {5'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer7_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (layer9_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_315 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign grp_fu_1734_p1 = 49'd276;

assign grp_fu_2313_p1 = 49'd458;

assign grp_fu_2314_p1 = 48'd246;

assign grp_fu_2667_p1 = 50'd871;

assign grp_fu_2721_p1 = 50'd572;

assign grp_fu_3047_p1 = 50'd845;

assign grp_fu_3109_p1 = 47'd106;

assign grp_fu_3116_p1 = 46'd39;

assign grp_fu_3138_p1 = 48'd157;

assign grp_fu_3792_p1 = 50'd558;

assign grp_fu_3838_p1 = 49'd444;

assign grp_fu_4514_p1 = 51'd1168;

assign grp_fu_4712_p1 = 51'd1045;

assign grp_fu_4886_p1 = 50'd667;

assign grp_fu_5108_p1 = 49'd465;

assign grp_fu_5110_p1 = 49'd307;

assign grp_fu_5174_p1 = 51'd1679;

assign grp_fu_521_p1 = 48'd166;

assign grp_fu_660_p1 = 49'd317;

assign grp_fu_912_p1 = 48'd172;

assign grp_fu_973_p1 = 47'd73;

assign i_9_fu_441063_p2 = (ap_sig_allocacmp_i + 8'd1);

assign icmp_ln25_fu_441057_p2 = ((ap_sig_allocacmp_i == 8'd216) ? 1'b1 : 1'b0);

assign layer9_out_din = $signed(or_ln46_s_fu_441700_p25);

assign or_ln46_s_fu_441700_p25 = {{{{{{{{{{{{{{{{{{{{{{{{add_ln42_23_fu_441695_p2}, {sext_ln70_19_fu_441691_p1}}, {sext_ln70_18_fu_441682_p1}}, {sext_ln42_17_fu_441674_p1}}, {sext_ln42_16_fu_441671_p1}}, {sext_ln42_15_fu_441668_p1}}, {sext_ln70_17_fu_441664_p1}}, {sext_ln70_16_fu_441655_p1}}, {sext_ln70_15_fu_441646_p1}}, {sext_ln70_14_fu_441637_p1}}, {sext_ln70_13_fu_441628_p1}}, {sext_ln70_12_fu_441619_p1}}, {sext_ln70_11_fu_441610_p1}}, {sext_ln70_10_fu_441601_p1}}, {sext_ln70_9_fu_441592_p1}}, {sext_ln70_8_fu_441583_p1}}, {sext_ln70_7_fu_441574_p1}}, {sext_ln70_6_fu_441565_p1}}, {sext_ln70_5_fu_441556_p1}}, {sext_ln70_4_fu_441547_p1}}, {sext_ln70_3_fu_441538_p1}}, {sext_ln70_2_fu_441529_p1}}, {sext_ln70_1_fu_441520_p1}}, {sext_ln70_fu_441511_p1}};

assign sext_ln42_15_fu_441668_p1 = $signed(add_ln42_18_reg_442086);

assign sext_ln42_16_fu_441671_p1 = $signed(add_ln42_19_reg_442091);

assign sext_ln42_17_fu_441674_p1 = $signed(add_ln42_20_reg_442096);

assign sext_ln42_21_fu_441410_p1 = $signed(and_ln73_1_fu_441403_p3);

assign sext_ln42_22_fu_441420_p1 = $signed(add_ln42_24_fu_441414_p2);

assign sext_ln42_23_fu_441448_p1 = $signed(and_ln73_3_fu_441441_p3);

assign sext_ln42_24_fu_441458_p1 = $signed(add_ln42_25_fu_441452_p2);

assign sext_ln42_25_fu_441486_p1 = $signed(and_ln73_5_fu_441479_p3);

assign sext_ln42_26_fu_441496_p1 = $signed(add_ln42_26_fu_441490_p2);

assign sext_ln70_10_fu_441601_p1 = $signed(add_ln42_10_fu_441596_p2);

assign sext_ln70_11_fu_441610_p1 = $signed(add_ln42_11_fu_441605_p2);

assign sext_ln70_12_fu_441619_p1 = $signed(add_ln42_12_fu_441614_p2);

assign sext_ln70_13_fu_441628_p1 = $signed(add_ln42_13_fu_441623_p2);

assign sext_ln70_14_fu_441637_p1 = $signed(add_ln42_14_fu_441632_p2);

assign sext_ln70_15_fu_441646_p1 = $signed(add_ln42_15_fu_441641_p2);

assign sext_ln70_16_fu_441655_p1 = $signed(add_ln42_16_fu_441650_p2);

assign sext_ln70_17_fu_441664_p1 = $signed(add_ln42_17_fu_441659_p2);

assign sext_ln70_18_fu_441682_p1 = $signed(add_ln42_21_fu_441677_p2);

assign sext_ln70_19_fu_441691_p1 = $signed(add_ln42_22_fu_441686_p2);

assign sext_ln70_1_fu_441520_p1 = $signed(add_ln42_1_fu_441515_p2);

assign sext_ln70_2_fu_441529_p1 = $signed(add_ln42_2_fu_441524_p2);

assign sext_ln70_3_fu_441538_p1 = $signed(add_ln42_3_fu_441533_p2);

assign sext_ln70_4_fu_441547_p1 = $signed(add_ln42_4_fu_441542_p2);

assign sext_ln70_5_fu_441556_p1 = $signed(add_ln42_5_fu_441551_p2);

assign sext_ln70_6_fu_441565_p1 = $signed(add_ln42_6_fu_441560_p2);

assign sext_ln70_7_fu_441574_p1 = $signed(add_ln42_7_fu_441569_p2);

assign sext_ln70_8_fu_441583_p1 = $signed(add_ln42_8_fu_441578_p2);

assign sext_ln70_9_fu_441592_p1 = $signed(add_ln42_9_fu_441587_p2);

assign sext_ln70_fu_441511_p1 = $signed(add_ln42_fu_441506_p2);

assign sext_ln73_3_fu_441399_p1 = $signed(and_ln_fu_441392_p3);

assign sext_ln73_4_fu_441437_p1 = $signed(and_ln73_2_fu_441430_p3);

assign sext_ln73_5_fu_441475_p1 = $signed(and_ln73_4_fu_441468_p3);

assign start_out = real_start;

always @ (posedge ap_clk) begin
    add_ln42_18_reg_442086[0] <= 1'b0;
    add_ln42_19_reg_442091[4:0] <= 5'b00000;
    add_ln42_20_reg_442096[1:0] <= 2'b00;
end

endmodule //myproject_normalize_array_ap_fixed_24u_array_ap_fixed_57_28_5_3_0_24u_config9_s
