// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer13_out_dout,
        layer13_out_num_data_valid,
        layer13_out_fifo_cap,
        layer13_out_empty_n,
        layer13_out_read,
        layer15_out_din,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_full_n,
        layer15_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [191:0] layer13_out_dout;
input  [1:0] layer13_out_num_data_valid;
input  [1:0] layer13_out_fifo_cap;
input   layer13_out_empty_n;
output   layer13_out_read;
output  [395:0] layer15_out_din;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;
input   layer15_out_full_n;
output   layer15_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer13_out_read;
reg layer15_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer13_out_blk_n;
reg    layer15_out_blk_n;
wire    ap_CS_fsm_state3;
wire   [24:0] mul_ln42_fu_140_p2;
reg   [24:0] mul_ln42_reg_769;
wire    ap_CS_fsm_state2;
wire   [25:0] mul_ln42_28_fu_143_p2;
reg   [25:0] mul_ln42_28_reg_773;
wire   [24:0] mul_ln42_29_fu_136_p2;
reg   [24:0] mul_ln42_29_reg_777;
wire   [24:0] mul_ln42_30_fu_137_p2;
reg   [24:0] mul_ln42_30_reg_781;
wire   [27:0] mul_ln42_31_fu_133_p2;
reg   [27:0] mul_ln42_31_reg_785;
wire   [23:0] mul_ln42_32_fu_141_p2;
reg   [23:0] mul_ln42_32_reg_789;
wire   [26:0] mul_ln42_33_fu_138_p2;
reg   [26:0] mul_ln42_33_reg_793;
wire   [26:0] mul_ln73_fu_142_p2;
reg   [26:0] mul_ln73_reg_797;
wire   [25:0] mul_ln73_3_fu_134_p2;
reg   [25:0] mul_ln73_3_reg_801;
wire   [22:0] mul_ln42_34_fu_139_p2;
reg   [22:0] mul_ln42_34_reg_805;
wire   [27:0] mul_ln42_35_fu_144_p2;
reg   [27:0] mul_ln42_35_reg_809;
wire   [24:0] mul_ln42_36_fu_135_p2;
reg   [24:0] mul_ln42_36_reg_813;
wire   [15:0] a_fu_818_p1;
reg  signed [15:0] a_reg_1129;
reg    ap_block_state1;
reg  signed [15:0] a_39_reg_1134;
reg  signed [15:0] a_29_reg_1139;
reg  signed [15:0] a_30_reg_1144;
reg  signed [15:0] a_31_reg_1149;
reg  signed [15:0] a_32_reg_1154;
reg  signed [15:0] a_33_reg_1159;
reg  signed [15:0] a_34_reg_1164;
reg  signed [15:0] a_35_reg_1169;
reg  signed [15:0] a_36_reg_1174;
reg  signed [15:0] a_37_reg_1179;
reg  signed [15:0] a_38_reg_1184;
wire   [12:0] mul_ln42_31_fu_133_p1;
wire  signed [9:0] mul_ln73_3_fu_134_p1;
wire   [9:0] mul_ln42_36_fu_135_p1;
wire   [9:0] mul_ln42_29_fu_136_p1;
wire  signed [9:0] mul_ln42_30_fu_137_p1;
wire  signed [11:0] mul_ln42_33_fu_138_p1;
wire   [7:0] mul_ln42_34_fu_139_p1;
wire   [9:0] mul_ln42_fu_140_p1;
wire  signed [8:0] mul_ln42_32_fu_141_p1;
wire   [10:0] mul_ln73_fu_142_p1;
wire   [10:0] mul_ln42_28_fu_143_p1;
wire   [12:0] mul_ln42_35_fu_144_p1;
wire   [24:0] add_ln42_fu_980_p2;
wire   [25:0] add_ln42_35_fu_990_p2;
wire   [24:0] add_ln42_36_fu_1000_p2;
wire   [24:0] add_ln42_37_fu_1010_p2;
wire   [27:0] add_ln42_38_fu_1020_p2;
wire   [23:0] add_ln42_39_fu_1030_p2;
wire   [26:0] add_ln42_40_fu_1040_p2;
wire   [26:0] add_ln42_41_fu_1050_p2;
wire   [25:0] add_ln42_42_fu_1060_p2;
wire   [22:0] add_ln42_43_fu_1070_p2;
wire   [27:0] add_ln42_44_fu_1080_p2;
wire   [24:0] add_ln42_45_fu_1090_p2;
wire  signed [32:0] sext_ln70_38_fu_1086_p1;
wire  signed [32:0] sext_ln70_37_fu_1076_p1;
wire  signed [32:0] sext_ln70_36_fu_1066_p1;
wire  signed [32:0] sext_ln70_35_fu_1056_p1;
wire  signed [32:0] sext_ln70_34_fu_1046_p1;
wire  signed [32:0] sext_ln70_33_fu_1036_p1;
wire  signed [32:0] sext_ln70_32_fu_1026_p1;
wire  signed [32:0] sext_ln70_31_fu_1016_p1;
wire  signed [32:0] sext_ln70_30_fu_1006_p1;
wire  signed [32:0] sext_ln70_29_fu_996_p1;
wire  signed [32:0] sext_ln70_fu_986_p1;
wire   [387:0] or_ln46_s_fu_1096_p13;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

myproject_mul_16s_13ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
mul_16s_13ns_28_1_1_U3353(
    .din0(a_31_reg_1149),
    .din1(mul_ln42_31_fu_133_p1),
    .dout(mul_ln42_31_fu_133_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U3354(
    .din0(a_35_reg_1169),
    .din1(mul_ln73_3_fu_134_p1),
    .dout(mul_ln73_3_fu_134_p2)
);

myproject_mul_16s_10ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10ns_25_1_1_U3355(
    .din0(a_38_reg_1184),
    .din1(mul_ln42_36_fu_135_p1),
    .dout(mul_ln42_36_fu_135_p2)
);

myproject_mul_16s_10ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10ns_25_1_1_U3356(
    .din0(a_29_reg_1139),
    .din1(mul_ln42_29_fu_136_p1),
    .dout(mul_ln42_29_fu_136_p2)
);

myproject_mul_16s_10s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_1_1_U3357(
    .din0(a_30_reg_1144),
    .din1(mul_ln42_30_fu_137_p1),
    .dout(mul_ln42_30_fu_137_p2)
);

myproject_mul_16s_12s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 27 ))
mul_16s_12s_27_1_1_U3358(
    .din0(a_33_reg_1159),
    .din1(mul_ln42_33_fu_138_p1),
    .dout(mul_ln42_33_fu_138_p2)
);

myproject_mul_16s_8ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 23 ))
mul_16s_8ns_23_1_1_U3359(
    .din0(a_36_reg_1174),
    .din1(mul_ln42_34_fu_139_p1),
    .dout(mul_ln42_34_fu_139_p2)
);

myproject_mul_16s_10ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10ns_25_1_1_U3360(
    .din0(a_reg_1129),
    .din1(mul_ln42_fu_140_p1),
    .dout(mul_ln42_fu_140_p2)
);

myproject_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U3361(
    .din0(a_32_reg_1154),
    .din1(mul_ln42_32_fu_141_p1),
    .dout(mul_ln42_32_fu_141_p2)
);

myproject_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U3362(
    .din0(a_34_reg_1164),
    .din1(mul_ln73_fu_142_p1),
    .dout(mul_ln73_fu_142_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U3363(
    .din0(a_39_reg_1134),
    .din1(mul_ln42_28_fu_143_p1),
    .dout(mul_ln42_28_fu_143_p2)
);

myproject_mul_16s_13ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
mul_16s_13ns_28_1_1_U3364(
    .din0(a_37_reg_1179),
    .din1(mul_ln42_35_fu_144_p1),
    .dout(mul_ln42_35_fu_144_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        a_29_reg_1139 <= {{layer13_out_dout[47:32]}};
        a_30_reg_1144 <= {{layer13_out_dout[63:48]}};
        a_31_reg_1149 <= {{layer13_out_dout[79:64]}};
        a_32_reg_1154 <= {{layer13_out_dout[95:80]}};
        a_33_reg_1159 <= {{layer13_out_dout[111:96]}};
        a_34_reg_1164 <= {{layer13_out_dout[127:112]}};
        a_35_reg_1169 <= {{layer13_out_dout[143:128]}};
        a_36_reg_1174 <= {{layer13_out_dout[159:144]}};
        a_37_reg_1179 <= {{layer13_out_dout[175:160]}};
        a_38_reg_1184 <= {{layer13_out_dout[191:176]}};
        a_39_reg_1134 <= {{layer13_out_dout[31:16]}};
        a_reg_1129 <= a_fu_818_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln42_28_reg_773 <= mul_ln42_28_fu_143_p2;
        mul_ln42_29_reg_777 <= mul_ln42_29_fu_136_p2;
        mul_ln42_30_reg_781 <= mul_ln42_30_fu_137_p2;
        mul_ln42_31_reg_785 <= mul_ln42_31_fu_133_p2;
        mul_ln42_32_reg_789 <= mul_ln42_32_fu_141_p2;
        mul_ln42_33_reg_793 <= mul_ln42_33_fu_138_p2;
        mul_ln42_34_reg_805 <= mul_ln42_34_fu_139_p2;
        mul_ln42_35_reg_809 <= mul_ln42_35_fu_144_p2;
        mul_ln42_36_reg_813 <= mul_ln42_36_fu_135_p2;
        mul_ln42_reg_769 <= mul_ln42_fu_140_p2;
        mul_ln73_3_reg_801 <= mul_ln73_3_fu_134_p2;
        mul_ln73_reg_797 <= mul_ln73_fu_142_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((layer15_out_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer13_out_blk_n = layer13_out_empty_n;
    end else begin
        layer13_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer13_out_read = 1'b1;
    end else begin
        layer13_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer15_out_blk_n = layer15_out_full_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer15_out_write = 1'b1;
    end else begin
        layer15_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_818_p1 = layer13_out_dout[15:0];

assign add_ln42_35_fu_990_p2 = (mul_ln42_28_reg_773 + 26'd2774016);

assign add_ln42_36_fu_1000_p2 = (mul_ln42_29_reg_777 + 25'd2014208);

assign add_ln42_37_fu_1010_p2 = (mul_ln42_30_reg_781 + 25'd1249280);

assign add_ln42_38_fu_1020_p2 = (mul_ln42_31_reg_785 + 28'd9772032);

assign add_ln42_39_fu_1030_p2 = (mul_ln42_32_reg_789 + 24'd824320);

assign add_ln42_40_fu_1040_p2 = (mul_ln42_33_reg_793 + 27'd4551680);

assign add_ln42_41_fu_1050_p2 = ($signed(mul_ln73_reg_797) + $signed(27'd133389312));

assign add_ln42_42_fu_1060_p2 = (mul_ln73_3_reg_801 + 26'd2088960);

assign add_ln42_43_fu_1070_p2 = ($signed(mul_ln42_34_reg_805) + $signed(23'd7684096));

assign add_ln42_44_fu_1080_p2 = ($signed(mul_ln42_35_reg_809) + $signed(28'd267915264));

assign add_ln42_45_fu_1090_p2 = ($signed(mul_ln42_36_reg_813) + $signed(25'd33186816));

assign add_ln42_fu_980_p2 = (mul_ln42_reg_769 + 25'd1024000);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer13_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer15_out_din = $signed(or_ln46_s_fu_1096_p13);

assign mul_ln42_28_fu_143_p1 = 26'd547;

assign mul_ln42_29_fu_136_p1 = 25'd311;

assign mul_ln42_30_fu_137_p1 = 25'd33554159;

assign mul_ln42_31_fu_133_p1 = 28'd2721;

assign mul_ln42_32_fu_141_p1 = 24'd16777073;

assign mul_ln42_33_fu_138_p1 = 27'd134216577;

assign mul_ln42_34_fu_139_p1 = 23'd98;

assign mul_ln42_35_fu_144_p1 = 28'd2252;

assign mul_ln42_36_fu_135_p1 = 25'd381;

assign mul_ln42_fu_140_p1 = 25'd280;

assign mul_ln73_3_fu_134_p1 = 26'd67108359;

assign mul_ln73_fu_142_p1 = 27'd1007;

assign or_ln46_s_fu_1096_p13 = {{{{{{{{{{{{add_ln42_45_fu_1090_p2}, {sext_ln70_38_fu_1086_p1}}, {sext_ln70_37_fu_1076_p1}}, {sext_ln70_36_fu_1066_p1}}, {sext_ln70_35_fu_1056_p1}}, {sext_ln70_34_fu_1046_p1}}, {sext_ln70_33_fu_1036_p1}}, {sext_ln70_32_fu_1026_p1}}, {sext_ln70_31_fu_1016_p1}}, {sext_ln70_30_fu_1006_p1}}, {sext_ln70_29_fu_996_p1}}, {sext_ln70_fu_986_p1}};

assign sext_ln70_29_fu_996_p1 = $signed(add_ln42_35_fu_990_p2);

assign sext_ln70_30_fu_1006_p1 = $signed(add_ln42_36_fu_1000_p2);

assign sext_ln70_31_fu_1016_p1 = $signed(add_ln42_37_fu_1010_p2);

assign sext_ln70_32_fu_1026_p1 = $signed(add_ln42_38_fu_1020_p2);

assign sext_ln70_33_fu_1036_p1 = $signed(add_ln42_39_fu_1030_p2);

assign sext_ln70_34_fu_1046_p1 = $signed(add_ln42_40_fu_1040_p2);

assign sext_ln70_35_fu_1056_p1 = $signed(add_ln42_41_fu_1050_p2);

assign sext_ln70_36_fu_1066_p1 = $signed(add_ln42_42_fu_1060_p2);

assign sext_ln70_37_fu_1076_p1 = $signed(add_ln42_43_fu_1070_p2);

assign sext_ln70_38_fu_1086_p1 = $signed(add_ln42_44_fu_1080_p2);

assign sext_ln70_fu_986_p1 = $signed(add_ln42_fu_980_p2);

assign start_out = real_start;

endmodule //myproject_normalize_array_ap_fixed_12u_array_ap_fixed_33_13_5_3_0_12u_config15_s
