-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer2_out_dout : IN STD_LOGIC_VECTOR (263 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_empty_n : IN STD_LOGIC;
    layer2_out_read : OUT STD_LOGIC;
    layer4_out_din : OUT STD_LOGIC_VECTOR (467 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer4_out_full_n : IN STD_LOGIC;
    layer4_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_12u_array_ap_fixed_39_20_5_3_0_12u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv37_54FF : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000101010011111111";
    constant ap_const_lv37_7514 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000111010100010100";
    constant ap_const_lv36_32A1 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000011001010100001";
    constant ap_const_lv35_11B0 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000001000110110000";
    constant ap_const_lv34_BA3 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000101110100011";
    constant ap_const_lv34_B83 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000101110000011";
    constant ap_const_lv34_8B7 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000100010110111";
    constant ap_const_lv37_4500 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000100010100000000";
    constant ap_const_lv35_1DAE : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000001110110101110";
    constant ap_const_lv32_316 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100010110";
    constant ap_const_lv36_26AF : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000010011010101111";
    constant ap_const_lv10_360 : STD_LOGIC_VECTOR (9 downto 0) := "1101100000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000100";
    constant ap_const_lv32_99 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011001";
    constant ap_const_lv32_9A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011010";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_C5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000101";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110001";
    constant ap_const_lv32_F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110010";
    constant ap_const_lv32_107 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000111";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv26_3FAB000 : STD_LOGIC_VECTOR (25 downto 0) := "11111110101011000000000000";
    constant ap_const_lv37_89E00 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000010001001111000000000";
    constant ap_const_lv37_1FFFF08C00 : STD_LOGIC_VECTOR (36 downto 0) := "1111111111111111100001000110000000000";
    constant ap_const_lv32_FFFAC800 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111110101100100000000000";
    constant ap_const_lv34_149A00 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000101001001101000000000";
    constant ap_const_lv35_93000 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000010010011000000000000";
    constant ap_const_lv36_FFFFAF800 : STD_LOGIC_VECTOR (35 downto 0) := "111111111111111110101111100000000000";
    constant ap_const_lv34_3FFFB9A00 : STD_LOGIC_VECTOR (33 downto 0) := "1111111111111110111001101000000000";
    constant ap_const_lv37_1FFFFF7200 : STD_LOGIC_VECTOR (36 downto 0) := "1111111111111111111110111001000000000";
    constant ap_const_lv34_3FFF41000 : STD_LOGIC_VECTOR (33 downto 0) := "1111111111111101000001000000000000";
    constant ap_const_lv35_7FFF92000 : STD_LOGIC_VECTOR (34 downto 0) := "11111111111111110010010000000000000";
    constant ap_const_lv36_A00 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000101000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln25_fu_466807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer2_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a_fu_466824_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_reg_467162 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_29_reg_467167 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_20_reg_467172 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_21_reg_467177 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_22_reg_467182 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_23_reg_467187 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_24_reg_467192 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_25_reg_467197 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_26_reg_467202 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_27_reg_467207 : STD_LOGIC_VECTOR (21 downto 0);
    signal a_28_reg_467212 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_reg_467217 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_reg_467217_pp0_iter2_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_reg_467217_pp0_iter3_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_683_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal mul_ln42_reg_467278 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_fu_663_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal mul_ln42_18_reg_467283 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln42_25_fu_467014_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_25_reg_467288 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_9903_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_19_reg_467293 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_6453_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln42_20_reg_467298 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_5276_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal mul_ln42_21_reg_467303 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_10518_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln42_22_reg_467308 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_fu_7235_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln42_23_reg_467313 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_8613_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal mul_ln42_24_reg_467318 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_fu_8330_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln42_25_reg_467323 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_9051_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal mul_ln42_26_reg_467328 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_4731_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln42_27_reg_467333 : STD_LOGIC_VECTOR (35 downto 0);
    signal i_02_fu_144 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal i_10_fu_466813_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_663_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_683_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_4731_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_5276_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_6453_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_7235_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_8330_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_8613_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_9051_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_9903_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_10518_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal and_ln_fu_466982_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal and_ln73_6_fu_466993_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln42_32_fu_467000_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_35_fu_467004_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_33_fu_467010_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln73_fu_466989_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_fu_467020_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln42_24_fu_467029_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln42_26_fu_467041_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_27_fu_467050_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_28_fu_467059_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln42_29_fu_467068_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln42_30_fu_467077_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_31_fu_467086_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln42_32_fu_467095_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_33_fu_467104_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln42_34_fu_467113_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal sext_ln70_28_fu_467109_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_27_fu_467100_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_26_fu_467091_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_25_fu_467082_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_24_fu_467073_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_23_fu_467064_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_22_fu_467055_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_21_fu_467046_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln42_22_fu_467038_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_20_fu_467034_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln70_fu_467025_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal or_ln46_s_fu_467118_p13 : STD_LOGIC_VECTOR (464 downto 0);
    signal grp_fu_663_ce : STD_LOGIC;
    signal grp_fu_683_ce : STD_LOGIC;
    signal grp_fu_4731_ce : STD_LOGIC;
    signal grp_fu_5276_ce : STD_LOGIC;
    signal grp_fu_6453_ce : STD_LOGIC;
    signal grp_fu_7235_ce : STD_LOGIC;
    signal grp_fu_8330_ce : STD_LOGIC;
    signal grp_fu_8613_ce : STD_LOGIC;
    signal grp_fu_9051_ce : STD_LOGIC;
    signal grp_fu_9903_ce : STD_LOGIC;
    signal grp_fu_10518_ce : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_221 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_22s_16ns_37_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (36 downto 0) );
    end component;


    component myproject_mul_22s_15ns_36_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component myproject_mul_22s_14ns_35_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (34 downto 0) );
    end component;


    component myproject_mul_22s_13ns_34_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component myproject_mul_22s_11ns_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_22s_16ns_37_3_1_U32 : component myproject_mul_22s_16ns_37_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 16,
        dout_WIDTH => 37)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_29_reg_467167,
        din1 => grp_fu_663_p1,
        ce => grp_fu_663_ce,
        dout => grp_fu_663_p2);

    mul_22s_16ns_37_3_1_U33 : component myproject_mul_22s_16ns_37_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 16,
        dout_WIDTH => 37)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_reg_467162,
        din1 => grp_fu_683_p1,
        ce => grp_fu_683_ce,
        dout => grp_fu_683_p2);

    mul_22s_15ns_36_3_1_U34 : component myproject_mul_22s_15ns_36_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 15,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_28_reg_467212,
        din1 => grp_fu_4731_p1,
        ce => grp_fu_4731_ce,
        dout => grp_fu_4731_p2);

    mul_22s_14ns_35_3_1_U35 : component myproject_mul_22s_14ns_35_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 14,
        dout_WIDTH => 35)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_22_reg_467182,
        din1 => grp_fu_5276_p1,
        ce => grp_fu_5276_ce,
        dout => grp_fu_5276_p2);

    mul_22s_13ns_34_3_1_U36 : component myproject_mul_22s_13ns_34_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 13,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_21_reg_467177,
        din1 => grp_fu_6453_p1,
        ce => grp_fu_6453_ce,
        dout => grp_fu_6453_p2);

    mul_22s_13ns_34_3_1_U37 : component myproject_mul_22s_13ns_34_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 13,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_24_reg_467192,
        din1 => grp_fu_7235_p1,
        ce => grp_fu_7235_ce,
        dout => grp_fu_7235_p2);

    mul_22s_13ns_34_3_1_U38 : component myproject_mul_22s_13ns_34_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 13,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_26_reg_467202,
        din1 => grp_fu_8330_p1,
        ce => grp_fu_8330_ce,
        dout => grp_fu_8330_p2);

    mul_22s_16ns_37_3_1_U39 : component myproject_mul_22s_16ns_37_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 16,
        dout_WIDTH => 37)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_25_reg_467197,
        din1 => grp_fu_8613_p1,
        ce => grp_fu_8613_ce,
        dout => grp_fu_8613_p2);

    mul_22s_14ns_35_3_1_U40 : component myproject_mul_22s_14ns_35_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 14,
        dout_WIDTH => 35)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_27_reg_467207,
        din1 => grp_fu_9051_p1,
        ce => grp_fu_9051_ce,
        dout => grp_fu_9051_p2);

    mul_22s_11ns_32_3_1_U41 : component myproject_mul_22s_11ns_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 11,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_20_reg_467172,
        din1 => grp_fu_9903_p1,
        ce => grp_fu_9903_ce,
        dout => grp_fu_9903_p2);

    mul_22s_15ns_36_3_1_U42 : component myproject_mul_22s_15ns_36_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 22,
        din1_WIDTH => 15,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_23_reg_467187,
        din1 => grp_fu_10518_p1,
        ce => grp_fu_10518_ce,
        dout => grp_fu_10518_p2);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_02_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_221)) then
                if ((icmp_ln25_fu_466807_p2 = ap_const_lv1_0)) then 
                    i_02_fu_144 <= i_10_fu_466813_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_02_fu_144 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_20_reg_467172 <= layer2_out_dout(87 downto 66);
                a_21_reg_467177 <= layer2_out_dout(109 downto 88);
                a_22_reg_467182 <= layer2_out_dout(131 downto 110);
                a_23_reg_467187 <= layer2_out_dout(153 downto 132);
                a_24_reg_467192 <= layer2_out_dout(175 downto 154);
                a_25_reg_467197 <= layer2_out_dout(197 downto 176);
                a_26_reg_467202 <= layer2_out_dout(219 downto 198);
                a_27_reg_467207 <= layer2_out_dout(241 downto 220);
                a_28_reg_467212 <= layer2_out_dout(263 downto 242);
                a_29_reg_467167 <= layer2_out_dout(43 downto 22);
                a_reg_467162 <= a_fu_466824_p1;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                tmp_reg_467217 <= layer2_out_dout(65 downto 44);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    add_ln42_25_reg_467288(33 downto 3) <= add_ln42_25_fu_467014_p2(33 downto 3);
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                mul_ln42_18_reg_467283 <= grp_fu_663_p2;
                mul_ln42_19_reg_467293 <= grp_fu_9903_p2;
                mul_ln42_20_reg_467298 <= grp_fu_6453_p2;
                mul_ln42_21_reg_467303 <= grp_fu_5276_p2;
                mul_ln42_22_reg_467308 <= grp_fu_10518_p2;
                mul_ln42_23_reg_467313 <= grp_fu_7235_p2;
                mul_ln42_24_reg_467318 <= grp_fu_8613_p2;
                mul_ln42_25_reg_467323 <= grp_fu_8330_p2;
                mul_ln42_26_reg_467328 <= grp_fu_9051_p2;
                mul_ln42_27_reg_467333 <= grp_fu_4731_p2;
                mul_ln42_reg_467278 <= grp_fu_683_p2;
                tmp_reg_467217_pp0_iter2_reg <= tmp_reg_467217;
                tmp_reg_467217_pp0_iter3_reg <= tmp_reg_467217_pp0_iter2_reg;
            end if;
        end if;
    end process;
    add_ln42_25_reg_467288(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_fu_466824_p1 <= layer2_out_dout(22 - 1 downto 0);
    add_ln42_24_fu_467029_p2 <= std_logic_vector(unsigned(mul_ln42_18_reg_467283) + unsigned(ap_const_lv37_1FFFF08C00));
    add_ln42_25_fu_467014_p2 <= std_logic_vector(signed(sext_ln42_33_fu_467010_p1) + signed(sext_ln73_fu_466989_p1));
    add_ln42_26_fu_467041_p2 <= std_logic_vector(unsigned(mul_ln42_19_reg_467293) + unsigned(ap_const_lv32_FFFAC800));
    add_ln42_27_fu_467050_p2 <= std_logic_vector(unsigned(mul_ln42_20_reg_467298) + unsigned(ap_const_lv34_149A00));
    add_ln42_28_fu_467059_p2 <= std_logic_vector(unsigned(mul_ln42_21_reg_467303) + unsigned(ap_const_lv35_93000));
    add_ln42_29_fu_467068_p2 <= std_logic_vector(unsigned(mul_ln42_22_reg_467308) + unsigned(ap_const_lv36_FFFFAF800));
    add_ln42_30_fu_467077_p2 <= std_logic_vector(unsigned(mul_ln42_23_reg_467313) + unsigned(ap_const_lv34_3FFFB9A00));
    add_ln42_31_fu_467086_p2 <= std_logic_vector(unsigned(mul_ln42_24_reg_467318) + unsigned(ap_const_lv37_1FFFFF7200));
    add_ln42_32_fu_467095_p2 <= std_logic_vector(unsigned(mul_ln42_25_reg_467323) + unsigned(ap_const_lv34_3FFF41000));
    add_ln42_33_fu_467104_p2 <= std_logic_vector(unsigned(mul_ln42_26_reg_467328) + unsigned(ap_const_lv35_7FFF92000));
    add_ln42_34_fu_467113_p2 <= std_logic_vector(unsigned(mul_ln42_27_reg_467333) + unsigned(ap_const_lv36_A00));
    add_ln42_35_fu_467004_p2 <= std_logic_vector(signed(sext_ln42_32_fu_467000_p1) + signed(ap_const_lv26_3FAB000));
    add_ln42_fu_467020_p2 <= std_logic_vector(unsigned(mul_ln42_reg_467278) + unsigned(ap_const_lv37_89E00));
    and_ln73_6_fu_466993_p3 <= (tmp_reg_467217_pp0_iter3_reg & ap_const_lv3_0);
    and_ln_fu_466982_p3 <= (tmp_reg_467217_pp0_iter3_reg & ap_const_lv11_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state6_pp0_stage0_iter5, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state6_pp0_stage0_iter5, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state6_pp0_stage0_iter5, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer2_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer2_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(layer4_out_full_n)
    begin
                ap_block_state6_pp0_stage0_iter5 <= (layer4_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_221_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_221 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln25_fu_466807_p2, ap_start_int)
    begin
        if (((icmp_ln25_fu_466807_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_02_fu_144, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i <= i_02_fu_144;
        end if; 
    end process;


    grp_fu_10518_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_10518_ce <= ap_const_logic_1;
        else 
            grp_fu_10518_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_10518_p1 <= ap_const_lv36_26AF(15 - 1 downto 0);

    grp_fu_4731_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_4731_ce <= ap_const_logic_1;
        else 
            grp_fu_4731_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_4731_p1 <= ap_const_lv36_32A1(15 - 1 downto 0);

    grp_fu_5276_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_5276_ce <= ap_const_logic_1;
        else 
            grp_fu_5276_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_5276_p1 <= ap_const_lv35_11B0(14 - 1 downto 0);

    grp_fu_6453_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_6453_ce <= ap_const_logic_1;
        else 
            grp_fu_6453_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_6453_p1 <= ap_const_lv34_BA3(13 - 1 downto 0);

    grp_fu_663_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_663_ce <= ap_const_logic_1;
        else 
            grp_fu_663_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_663_p1 <= ap_const_lv37_54FF(16 - 1 downto 0);

    grp_fu_683_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_683_ce <= ap_const_logic_1;
        else 
            grp_fu_683_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_683_p1 <= ap_const_lv37_7514(16 - 1 downto 0);

    grp_fu_7235_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_7235_ce <= ap_const_logic_1;
        else 
            grp_fu_7235_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_7235_p1 <= ap_const_lv34_B83(13 - 1 downto 0);

    grp_fu_8330_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_8330_ce <= ap_const_logic_1;
        else 
            grp_fu_8330_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_8330_p1 <= ap_const_lv34_8B7(13 - 1 downto 0);

    grp_fu_8613_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_8613_ce <= ap_const_logic_1;
        else 
            grp_fu_8613_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_8613_p1 <= ap_const_lv37_4500(16 - 1 downto 0);

    grp_fu_9051_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_9051_ce <= ap_const_logic_1;
        else 
            grp_fu_9051_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_9051_p1 <= ap_const_lv35_1DAE(14 - 1 downto 0);

    grp_fu_9903_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_9903_ce <= ap_const_logic_1;
        else 
            grp_fu_9903_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_9903_p1 <= ap_const_lv32_316(11 - 1 downto 0);
    i_10_fu_466813_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv10_1));
    icmp_ln25_fu_466807_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv10_360) else "0";

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer2_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_empty_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer2_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_read <= ap_const_logic_1;
        else 
            layer2_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, layer4_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            layer4_out_blk_n <= layer4_out_full_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer4_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln46_s_fu_467118_p13),468));


    layer4_out_write_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            layer4_out_write <= ap_const_logic_1;
        else 
            layer4_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln46_s_fu_467118_p13 <= (((((((((((add_ln42_34_fu_467113_p2 & sext_ln70_28_fu_467109_p1) & sext_ln70_27_fu_467100_p1) & sext_ln70_26_fu_467091_p1) & sext_ln70_25_fu_467082_p1) & sext_ln70_24_fu_467073_p1) & sext_ln70_23_fu_467064_p1) & sext_ln70_22_fu_467055_p1) & sext_ln70_21_fu_467046_p1) & sext_ln42_22_fu_467038_p1) & sext_ln70_20_fu_467034_p1) & sext_ln70_fu_467025_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln42_22_fu_467038_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_25_reg_467288),39));

        sext_ln42_32_fu_467000_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln73_6_fu_466993_p3),26));

        sext_ln42_33_fu_467010_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_35_fu_467004_p2),34));

        sext_ln70_20_fu_467034_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_24_fu_467029_p2),39));

        sext_ln70_21_fu_467046_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_26_fu_467041_p2),39));

        sext_ln70_22_fu_467055_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_27_fu_467050_p2),39));

        sext_ln70_23_fu_467064_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_28_fu_467059_p2),39));

        sext_ln70_24_fu_467073_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_29_fu_467068_p2),39));

        sext_ln70_25_fu_467082_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_30_fu_467077_p2),39));

        sext_ln70_26_fu_467091_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_31_fu_467086_p2),39));

        sext_ln70_27_fu_467100_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_32_fu_467095_p2),39));

        sext_ln70_28_fu_467109_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_33_fu_467104_p2),39));

        sext_ln70_fu_467025_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_fu_467020_p2),39));

        sext_ln73_fu_466989_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln_fu_466982_p3),34));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
