-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_compute_output_buffer_2d_array_array_ap_fixed_22_13_5_3_0_12u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
    layer2_out_din : OUT STD_LOGIC_VECTOR (263 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer2_out_full_n : IN STD_LOGIC;
    layer2_out_write : OUT STD_LOGIC;
    layer2_out_blk_n : OUT STD_LOGIC );
end;


architecture behav of myproject_compute_output_buffer_2d_array_array_ap_fixed_22_13_5_3_0_12u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal sX_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln284_reg_379 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_1_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal and_ln284_1_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_reg_387 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln313_fu_294_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_out_reg_399 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal res_out_1_reg_404 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_2_reg_409 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_3_reg_414 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_4_reg_419 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_5_reg_424 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_6_reg_429 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_7_reg_434 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_8_reg_439 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_9_reg_444 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_24_reg_449 : STD_LOGIC_VECTOR (21 downto 0);
    signal res_out_25_reg_454 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_predicate_op60_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_done : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_idle : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ready : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter1_ignore_call2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp6 : BOOLEAN;
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce : STD_LOGIC;
    signal ap_predicate_op22_call_state2 : BOOLEAN;
    signal ap_predicate_op43_call_state3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp22 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_ignoreCallOp43 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_reg_81 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln307_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal select_ln318_fu_238_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln307_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln303_fu_214_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_323_fu_170_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_324_fu_186_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln284_4_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_5_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_1_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln318_fu_232_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln313_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln313_fu_288_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_301 : BOOLEAN;
    signal ap_condition_229 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_uint_1_1u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component myproject_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (21 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92 : component myproject_shift_line_buffer_array_ap_uint_1_1u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start,
        ap_done => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_done,
        ap_idle => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_idle,
        ap_ready => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ready,
        in_elem_0_0_0_0_0_val => in_elem_0_0_0_0_0_val,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld,
        ap_ce => call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce);

    grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120 : component myproject_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        ap_return_0 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3,
        ap_return_4 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4,
        ap_return_5 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5,
        ap_return_6 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6,
        ap_return_7 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7,
        ap_return_8 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8,
        ap_return_9 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9,
        ap_return_10 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10,
        ap_return_11 => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11,
        ap_ce => grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_storemerge_reg_81_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_301)) then
                if ((icmp_ln307_fu_270_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_81 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_270_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_81 <= select_ln313_fu_294_p3;
                end if;
            end if; 
        end if;
    end process;

    pX_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if ((icmp_ln303_fu_220_p2 = ap_const_lv1_1)) then 
                    pX_2 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_220_p2 = ap_const_lv1_0)) then 
                    pX_2 <= add_ln303_fu_214_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_301)) then
                if ((icmp_ln307_fu_270_p2 = ap_const_lv1_1)) then 
                    pY_2 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_270_p2 = ap_const_lv1_0)) then 
                    pY_2 <= add_ln307_fu_264_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_229)) then
                if ((icmp_ln303_fu_220_p2 = ap_const_lv1_1)) then 
                    sX_2 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_220_p2 = ap_const_lv1_0)) then 
                    sX_2 <= select_ln318_fu_238_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                and_ln284_1_reg_383 <= and_ln284_1_fu_208_p2;
                icmp_ln284_reg_379 <= icmp_ln284_fu_146_p2;
                icmp_ln303_reg_387 <= icmp_ln303_fu_220_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                res_out_1_reg_404 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_1;
                res_out_24_reg_449 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_10;
                res_out_25_reg_454 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_11;
                res_out_2_reg_409 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_2;
                res_out_3_reg_414 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_3;
                res_out_4_reg_419 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_4;
                res_out_5_reg_424 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_5;
                res_out_6_reg_429 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_6;
                res_out_7_reg_434 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_7;
                res_out_8_reg_439 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_8;
                res_out_9_reg_444 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_9;
                res_out_reg_399 <= grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln303_reg_387 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                sY_2 <= ap_phi_reg_pp0_iter0_storemerge_reg_81;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln303_fu_214_p2 <= std_logic_vector(unsigned(pX_2) + unsigned(ap_const_lv32_1));
    add_ln307_fu_264_p2 <= std_logic_vector(unsigned(pY_2) + unsigned(ap_const_lv32_1));
    add_ln313_fu_288_p2 <= std_logic_vector(unsigned(sY_2) + unsigned(ap_const_lv32_1));
    add_ln318_fu_232_p2 <= std_logic_vector(unsigned(sX_2) + unsigned(ap_const_lv32_1));
    and_ln284_1_fu_208_p2 <= (icmp_ln284_1_fu_164_p2 and and_ln284_fu_202_p2);
    and_ln284_fu_202_p2 <= (icmp_ln284_5_fu_196_p2 and icmp_ln284_4_fu_180_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1_ignore_call2)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp6 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_ignore_call2));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_ce, ap_block_state4_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001_ignoreCallOp22 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001_ignoreCallOp43 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(layer2_out_full_n, ap_predicate_op60_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((layer2_out_full_n = ap_const_logic_0) and (ap_predicate_op60_write_state4 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage0_iter1_ignore_call2_assign_proc : process(layer2_out_full_n, ap_predicate_op60_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1_ignore_call2 <= ((layer2_out_full_n = ap_const_logic_0) and (ap_predicate_op60_write_state4 = ap_const_boolean_1));
    end process;


    ap_condition_229_assign_proc : process(ap_enable_reg_pp0_iter0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_229 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_condition_301_assign_proc : process(ap_enable_reg_pp0_iter0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln303_fu_220_p2)
    begin
                ap_condition_301 <= ((icmp_ln303_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op22_call_state2_assign_proc : process(icmp_ln284_fu_146_p2, and_ln284_1_fu_208_p2)
    begin
                ap_predicate_op22_call_state2 <= ((icmp_ln284_fu_146_p2 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln284_1_fu_208_p2));
    end process;


    ap_predicate_op43_call_state3_assign_proc : process(icmp_ln284_reg_379, and_ln284_1_reg_383)
    begin
                ap_predicate_op43_call_state3 <= ((ap_const_lv1_1 = and_ln284_1_reg_383) and (icmp_ln284_reg_379 = ap_const_lv1_1));
    end process;


    ap_predicate_op60_write_state4_assign_proc : process(icmp_ln284_reg_379, and_ln284_1_reg_383)
    begin
                ap_predicate_op60_write_state4 <= ((ap_const_lv1_1 = and_ln284_1_reg_383) and (icmp_ln284_reg_379 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp6)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp6) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_uint_1_1u_config2_s_fu_92_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_ignoreCallOp22, ap_block_pp0_stage2_11001_ignoreCallOp43)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_ignoreCallOp43) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp22) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))))) then 
            grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_latency_ap_uint_1_ap_fixed_22_13_5_3_0_config2_mult_s_fu_120_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln284_1_fu_164_p2 <= "1" when (sY_2 = ap_const_lv32_2) else "0";
    icmp_ln284_4_fu_180_p2 <= "1" when (signed(tmp_323_fu_170_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_5_fu_196_p2 <= "1" when (signed(tmp_324_fu_186_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_fu_146_p2 <= "1" when (sX_2 = ap_const_lv32_2) else "0";
    icmp_ln303_fu_220_p2 <= "1" when (add_ln303_fu_214_p2 = ap_const_lv32_26) else "0";
    icmp_ln307_fu_270_p2 <= "1" when (add_ln307_fu_264_p2 = ap_const_lv32_1A) else "0";
    icmp_ln313_fu_282_p2 <= "1" when (sY_2 = ap_const_lv32_2) else "0";

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer2_out_full_n, ap_block_pp0_stage0, icmp_ln284_reg_379, and_ln284_1_reg_383)
    begin
        if (((ap_const_lv1_1 = and_ln284_1_reg_383) and (icmp_ln284_reg_379 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_full_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer2_out_din <= (((((((((((res_out_25_reg_454 & res_out_24_reg_449) & res_out_9_reg_444) & res_out_8_reg_439) & res_out_7_reg_434) & res_out_6_reg_429) & res_out_5_reg_424) & res_out_4_reg_419) & res_out_3_reg_414) & res_out_2_reg_409) & res_out_1_reg_404) & res_out_reg_399);

    layer2_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_predicate_op60_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op60_write_state4 = ap_const_boolean_1))) then 
            layer2_out_write <= ap_const_logic_1;
        else 
            layer2_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln313_fu_294_p3 <= 
        ap_const_lv32_2 when (icmp_ln313_fu_282_p2(0) = '1') else 
        add_ln313_fu_288_p2;
    select_ln318_fu_238_p3 <= 
        ap_const_lv32_2 when (icmp_ln284_fu_146_p2(0) = '1') else 
        add_ln318_fu_232_p2;
    tmp_323_fu_170_p4 <= pY_2(31 downto 1);
    tmp_324_fu_186_p4 <= pX_2(31 downto 1);
end behav;
